/* Generated by Cython 0.29.33 */

#ifndef __PYX_HAVE__imate___c_trace_estimator__py_c_trace_estimator
#define __PYX_HAVE__imate___c_trace_estimator__py_c_trace_estimator

#include "Python.h"

#ifndef __PYX_HAVE_API__imate___c_trace_estimator__py_c_trace_estimator

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C void lapack_sstev(char *, int *, float *, float *, float *, int *, float *, int *);
__PYX_EXTERN_C void lapack_dstev(char *, int *, double *, double *, double *, int *, double *, int *);
__PYX_EXTERN_C void lapack_sbdsdc(char *, char *, int *, float *, float *, float *, int *, float *, int *, float *, int *, float *, int *, int *);
__PYX_EXTERN_C void lapack_dbdsdc(char *, char *, int *, double *, double *, double *, int *, double *, int *, double *, int *, double *, int *, int *);
__PYX_EXTERN_C double erf_inv(double);

#endif /* !__PYX_HAVE_API__imate___c_trace_estimator__py_c_trace_estimator */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initpy_c_trace_estimator(void);
#else
PyMODINIT_FUNC PyInit_py_c_trace_estimator(void);
#endif

#endif /* !__PYX_HAVE__imate___c_trace_estimator__py_c_trace_estimator */
