imate: cuVectorOperations< DataType > Class Template Reference
cuVectorOperations< DataType > Class Template Reference
A static class for vector operations, similar to level-1 operations of the BLAS library. This class acts as a templated namespace, where all member methods are public and static.
#include <cu_vector_operations.h>
Static Public Member Functions
static void copy_vector (cublasHandle_t cublas_handle, const DataType *input_vector, const LongIndexType vector_size, DataType *output_vector)
Copies a vector to a new vector. Result is written in-place.
static void copy_scaled_vector (cublasHandle_t cublas_handle, const DataType *input_vector, const LongIndexType vector_size, const DataType scale, DataType *output_vector)
Scales a vector and stores to a new vector.
static void subtract_scaled_vector (cublasHandle_t cublas_handle, const DataType *input_vector, const LongIndexType vector_size, const DataType scale, DataType *output_vector)
Subtracts the scaled input vector from the output vector.
static DataType inner_product (cublasHandle_t cublas_handle, const DataType *vector1, const DataType *vector2, const LongIndexType vector_size)
Computes Euclidean inner product of two vectors.
static DataType euclidean_norm (cublasHandle_t cublas_handle, const DataType *vector, const LongIndexType vector_size)
Computes the Euclidean 2-norm of a 1D array.
static DataType normalize_vector_in_place (cublasHandle_t cublas_handle, DataType *vector, const LongIndexType vector_size)
Normalizes a vector based on Euclidean 2-norm. The result is written in-place.
static DataType normalize_vector_and_copy (cublasHandle_t cublas_handle, const DataType *vector, const LongIndexType vector_size, DataType *output_vector)
Normalizes a vector based on Euclidean 2-norm. The result is written into another vector.
Detailed Description
template<typename DataType>
class cuVectorOperations< DataType >
A static class for vector operations, similar to level-1 operations of the BLAS library. This class acts as a templated namespace, where all member methods are public and static.
See also
MatrixOperations
Definition at line 36 of file cu_vector_operations.h.
Member Function Documentation
copy_scaled_vector()
template<typename DataType > void cuVectorOperations< DataType >::copy_scaled_vector (cublasHandle_t cublas_handle, const DataType * input_vector, const LongIndexType vector_size, const DataType scale, DataType * output_vector) static
Scales a vector and stores to a new vector.
Parameters
[in] cublas_handle The cuBLAS object handle.
[in] input_vector A 1D array
[in] vector_size Length of vector array
[in] scale Scale coefficient to the input vector. If this is equal to one, the function effectively becomes the same as copy_vector.
[out] output_vector Output vector (written in place).
Definition at line 73 of file cu_vector_operations.cu.
 {
     cublasStatus_t status;
     int incx = 1;
     int incy = 1;
     // Copy input to output vector
     status = cublas_interface::cublasXcopy(cublas_handle, vector_size,
                                            input_vector, incx,
                                            output_vector, incy);
     assert(status == CUBLAS_STATUS_SUCCESS);
     // Scale outpu vector
     status = cublas_interface::cublasXscal(cublas_handle, vector_size, &scale,
                                            output_vector, incy);
     assert(status == CUBLAS_STATUS_SUCCESS);
 }
References cublas_interface::cublasXcopy(), and cublas_interface::cublasXscal().
Referenced by cu_lanczos_tridiagonalization(), and cuVectorOperations< DataType >::normalize_vector_and_copy().
copy_vector()
template<typename DataType > void cuVectorOperations< DataType >::copy_vector (cublasHandle_t cublas_handle, const DataType * input_vector, const LongIndexType vector_size, DataType * output_vector) static
Copies a vector to a new vector. Result is written in-place.
Parameters
[in] cublas_handle The cuBLAS object handle.
[in] input_vector A 1D array
[in] vector_size Length of vector array
[out] output_vector Output vector (written in place).
Definition at line 38 of file cu_vector_operations.cu.
 {
     int incx = 1;
     int incy = 1;
     cublasStatus_t status = cublas_interface::cublasXcopy(
             cublas_handle, vector_size, input_vector, incx, output_vector,
             incy);
     assert(status == CUBLAS_STATUS_SUCCESS);
 }
References cublas_interface::cublasXcopy().
euclidean_norm()
template<typename DataType > DataType cuVectorOperations< DataType >::euclidean_norm (cublasHandle_t cublas_handle, const DataType * vector, const LongIndexType vector_size) static
Computes the Euclidean 2-norm of a 1D array.
Parameters
[in] cublas_handle The cuBLAS object handle.
[in] vector A pointer to 1D array
[in] vector_size Length of the array
Returns
Euclidean norm
Definition at line 201 of file cu_vector_operations.cu.
 {
     DataType norm;
     int incx = 1;
     cublasStatus_t status = cublas_interface::cublasXnrm2(
             cublas_handle, vector_size, vector, incx, &norm);
     assert(status == CUBLAS_STATUS_SUCCESS);
     return norm;
 }
References cublas_interface::cublasXnrm2().
Referenced by cu_lanczos_tridiagonalization(), cuOrthogonalization< DataType >::gram_schmidt_process(), cuVectorOperations< DataType >::normalize_vector_and_copy(), cuVectorOperations< DataType >::normalize_vector_in_place(), and cuOrthogonalization< DataType >::orthogonalize_vectors().
inner_product()
template<typename DataType > DataType cuVectorOperations< DataType >::inner_product (cublasHandle_t cublas_handle, const DataType * vector1, const DataType * vector2, const LongIndexType vector_size) static
Computes Euclidean inner product of two vectors.
Parameters
[in] cublas_handle The cuBLAS object handle.
[in] vector1 1D array
[in] vector2 1D array
[in] vector_size Length of array
Returns
Inner product of two vectors.
Definition at line 166 of file cu_vector_operations.cu.
 {
     DataType inner_prod;
     int incx = 1;
     int incy = 1;
     cublasStatus_t status = cublas_interface::cublasXdot(
             cublas_handle, vector_size, vector1, incx, vector2, incy,
             &inner_prod);
     assert(status == CUBLAS_STATUS_SUCCESS);
     return inner_prod;
 }
References cublas_interface::cublasXdot().
Referenced by cu_lanczos_tridiagonalization(), cuOrthogonalization< DataType >::gram_schmidt_process(), and cuOrthogonalization< DataType >::orthogonalize_vectors().
normalize_vector_and_copy()
template<typename DataType > DataType cuVectorOperations< DataType >::normalize_vector_and_copy (cublasHandle_t cublas_handle, const DataType * vector, const LongIndexType vector_size, DataType * output_vector) static
Normalizes a vector based on Euclidean 2-norm. The result is written into another vector.
Parameters
[in] cublas_handle The cuBLAS object handle.
[in] vector Input vector.
[in] vector_size Length of the input vector
[out] output_vector Output vector, which is the normalization of the input vector.
Returns
2-norm of the input vector
Definition at line 273 of file cu_vector_operations.cu.
 {
     // Norm of vector
     DataType norm = cuVectorOperations<DataType>::euclidean_norm(
             cublas_handle, vector, vector_size);
     // Normalize to output
     DataType scale = 1.0 / norm;
     cuVectorOperations<DataType>::copy_scaled_vector(cublas_handle, vector,
                                                      vector_size, scale,
                                                      output_vector);
     return norm;
 }
References cuVectorOperations< DataType >::copy_scaled_vector(), and cuVectorOperations< DataType >::euclidean_norm().
normalize_vector_in_place()
template<typename DataType > DataType cuVectorOperations< DataType >::normalize_vector_in_place (cublasHandle_t cublas_handle, DataType * vector, const LongIndexType vector_size) static
Normalizes a vector based on Euclidean 2-norm. The result is written in-place.
Parameters
[in] cublas_handle The cuBLAS object handle.
[in,out] vector Input vector to be normalized in-place.
[in] vector_size Length of the input vector
Returns
2-Norm of the input vector (before normalization)
Definition at line 234 of file cu_vector_operations.cu.
 {
     // Norm of vector
     DataType norm = cuVectorOperations<DataType>::euclidean_norm(
             cublas_handle, vector, vector_size);
     // Normalize in place
     DataType scale = 1.0 / norm;
     int incx = 1;
     cublasStatus_t status = cublas_interface::cublasXscal(
             cublas_handle, vector_size, &scale, vector, incx);
     assert(status == CUBLAS_STATUS_SUCCESS);
     return norm;
 }
References cublas_interface::cublasXscal(), and cuVectorOperations< DataType >::euclidean_norm().
Referenced by cu_golub_kahn_bidiagonalization().
subtract_scaled_vector()
template<typename DataType > void cuVectorOperations< DataType >::subtract_scaled_vector (cublasHandle_t cublas_handle, const DataType * input_vector, const LongIndexType vector_size, const DataType scale, DataType * output_vector) static
Subtracts the scaled input vector from the output vector.
Performs the following operation:
\[ \boldsymbol{b} = \boldsymbol{b} - c \boldsymbol{a}, \]
where
\(\boldsymbol{a} \) is the input vector,
\(c \) is a scalar scale to the input vector, and
\(\boldsymbol{b} \) is the output vector that is written in-place.
Parameters
[in] cublas_handle The cuBLAS object handle.
[in] input_vector A 1D array
[in] vector_size Length of vector array
[in] scale Scale coefficient to the input vector.
[in,out] output_vector Output vector (written in place).
Definition at line 126 of file cu_vector_operations.cu.
 {
     if (scale == 0.0)
     {
         return;
     }
     int incx = 1;
     int incy = 1;
     DataType neg_scale = -scale;
     cublasStatus_t status = cublas_interface::cublasXaxpy(
             cublas_handle, vector_size, &neg_scale, input_vector, incx,
             output_vector, incy);
     assert(status == CUBLAS_STATUS_SUCCESS);
 }
References cublas_interface::cublasXaxpy().
Referenced by cuAffineMatrixFunction< DataType >::_add_scaled_vector(), cu_golub_kahn_bidiagonalization(), cu_lanczos_tridiagonalization(), cuOrthogonalization< DataType >::gram_schmidt_process(), and cuOrthogonalization< DataType >::orthogonalize_vectors().
The documentation for this class was generated from the following files:
/home/sia/work/ADCP/Noise-Estimation/code/imate/imate/_cu_basic_algebra/cu_vector_operations.h
/home/sia/work/ADCP/Noise-Estimation/code/imate/imate/_cu_basic_algebra/cu_vector_operations.cu