imate: imate.sample_matrices._sparse_correlation_matrix Namespace Reference
imate.sample_matrices._sparse_correlation_matrix Namespace Reference
Functions
def _ball_radius (volume, dimension)
def _estimate_kernel_threshold (matrix_size, dimension, density, scale, kernel, kernel_param)
def _estimate_max_nnz (matrix_size, dimension, density)
def sparse_correlation_matrix (coords, scale=0.1, kernel='exponential', kernel_param=None, density=0.001, format=r 'csr', dtype=r 'float64', verbose=False)
Variables
list __all__ = ['sparse_correlation_matrix']
thread_data
int percent_update = 20
chunk_size = 1
matrix_size
schedule
chunksize
int progress = percent_update * counter[0] // \
Function Documentation
_ball_radius()
def imate.sample_matrices._sparse_correlation_matrix._ball_radius (volume, dimension) private
Computes the radius of n-ball at dimension n, given its volume.
:param volume: Volume of n-ball
:type volume: double
:param dimension: Dimension of embedding space
:type dimension: int
:return: radius of n-ball
:rtype: double
Definition at line 253 of file _sparse_correlation_matrix.pyx.
 def _ball_radius(volume, dimension):
     """
     Computes the radius of n-ball at dimension n, given its volume.
     :param volume: Volume of n-ball
     :type volume: double
     :param dimension: Dimension of embedding space
     :type dimension: int
     :return: radius of n-ball
     :rtype: double
     """
     # Compute Gamma(dimension/2 + 1)
     if dimension % 2 == 0:
         k = 0.5 * dimension
         gamma = 1.0
         while k > 0.0:
             gamma *= k
             k -= 1.0
     else:
         k = numpy.ceil(0.5 * dimension)
         gamma = numpy.sqrt(numpy.pi)
         while k > 0.0:
             gamma *= k - 0.5
             k -= 1.0
     # radius from volume
     radius = (gamma * volume)**(1.0 / dimension) / numpy.sqrt(numpy.pi)
     return radius
 # =========================
 # estimate kernel threshold
 # =========================
Referenced by imate.sample_matrices._sparse_correlation_matrix._estimate_kernel_threshold(), and imate.sample_matrices._sparse_correlation_matrix._estimate_max_nnz().
_estimate_kernel_threshold()
def imate.sample_matrices._sparse_correlation_matrix._estimate_kernel_threshold (matrix_size, dimension, density, scale, kernel, kernel_param) private
Estimates the kernel's tapering threshold to sparsify a dense matrix into a
sparse matrix with the requested density.
Here is how density :math:`\\rho` is related to the kernel_threshold
:math:`\\tau`:
.. math::
    a = \\rho n = \\mathrm{Vol}_{d}(r/l),
    \\tau = k(r),
where:
    * :math:`n` is the number of points in the unit hypercube, also it is
      the matrix size.
    * :math:`d` is the dimension of space.
    * :math:`\\mathrm{Vol}_{d}(r/l)` is the volume of d-ball of radius
      :math:`r/l`.
    * :math:`l = 1/(\\sqrt[d]{n} - 1)` is the grid size along each axis,
      assuming the points are places on an equi-distanced structured grid.
    * :math:`k` is the Matern correlation function.
    * :math:`a` is the adjacency of a point, which is the number of
      the neighbor points that are correlated to a point.
    * :math:`\\rho` is the sparse matrix density (input to this function).
    * :math:`\\tau` is the kernel threshold (output of this function).
The adjacency :math:`a` is the number of points on an integer lattice
and inside a d-ball. This quantity can be approximated by the volume of a
d-ball, see for instance
`Gauss circle problem<https://en.wikipedia.org/wiki/Gauss_circle_problem>`_
 in 2D.
A non-zero kernel threshold is used to sparsify a matrix by tapering its
correlation function. However, if the kernel threshold is too large, some
elements of the correlation matrix will not be correlated to any other
neighbor point. This leads to a correlation matrix with some rows that have
only one non-zero element equal to one on the diagonal and zero elsewhere.
Essentially, if all points loose their correlation to a neighbor, the
matrix becomes identity.
This function checks if a set of parameters to form a sparse matrix could
lead to this issue. The correlation matrix in this module is formed by the
mutual correlation between spatial set of points in the unit hypercube. We
assume each point is surrounded by a sphere of the radius of the kernel
threshold. If this radius is large enough, then the sphere of all points
intersect. If the criteria is not met, this function raises ``ValueError``.
:param matrix_size: The size of the square matrix. This is also the number
    of points used to construct the correlation matrix.
:type matrix_size: int
:param dimension: The dimension of the space of points used to construct
    the correlation matrix.
:type dimension: int
:param sparse_density: The desired density of the sparse matrix. Note that
    the actual density of the generated matrix will not be exactly equal to
    this value. If the matrix size is large, this value is close to the
    actual matrix density.
:type sparse_density: int
:param scale: A parameter of correlation function that scales
    distance.
:type scale: float
:param nu: The parameter :math:`\\nu` of Matern correlation kernel.
:type nu: float
:return: Kernel threshold level
:rtype: double
Definition at line 291 of file _sparse_correlation_matrix.pyx.
         kernel_param):
     """
     Estimates the kernel's tapering threshold to sparsify a dense matrix into a
     sparse matrix with the requested density.
     Here is how density :math:`\\rho` is related to the kernel_threshold
     :math:`\\tau`:
     .. math::
         a = \\rho n = \\mathrm{Vol}_{d}(r/l),
         \\tau = k(r),
     where:
         * :math:`n` is the number of points in the unit hypercube, also it is
           the matrix size.
         * :math:`d` is the dimension of space.
         * :math:`\\mathrm{Vol}_{d}(r/l)` is the volume of d-ball of radius
           :math:`r/l`.
         * :math:`l = 1/(\\sqrt[d]{n} - 1)` is the grid size along each axis,
           assuming the points are places on an equi-distanced structured grid.
         * :math:`k` is the Matern correlation function.
         * :math:`a` is the adjacency of a point, which is the number of
           the neighbor points that are correlated to a point.
         * :math:`\\rho` is the sparse matrix density (input to this function).
         * :math:`\\tau` is the kernel threshold (output of this function).
     The adjacency :math:`a` is the number of points on an integer lattice
     and inside a d-ball. This quantity can be approximated by the volume of a
     d-ball, see for instance
     `Gauss circle problem<https://en.wikipedia.org/wiki/Gauss_circle_problem>`_
      in 2D.
     A non-zero kernel threshold is used to sparsify a matrix by tapering its
     correlation function. However, if the kernel threshold is too large, some
     elements of the correlation matrix will not be correlated to any other
     neighbor point. This leads to a correlation matrix with some rows that have
     only one non-zero element equal to one on the diagonal and zero elsewhere.
     Essentially, if all points loose their correlation to a neighbor, the
     matrix becomes identity.
     This function checks if a set of parameters to form a sparse matrix could
     lead to this issue. The correlation matrix in this module is formed by the
     mutual correlation between spatial set of points in the unit hypercube. We
     assume each point is surrounded by a sphere of the radius of the kernel
     threshold. If this radius is large enough, then the sphere of all points
     intersect. If the criteria is not met, this function raises ``ValueError``.
     :param matrix_size: The size of the square matrix. This is also the number
         of points used to construct the correlation matrix.
     :type matrix_size: int
     :param dimension: The dimension of the space of points used to construct
         the correlation matrix.
     :type dimension: int
     :param sparse_density: The desired density of the sparse matrix. Note that
         the actual density of the generated matrix will not be exactly equal to
         this value. If the matrix size is large, this value is close to the
         actual matrix density.
     :type sparse_density: int
     :param scale: A parameter of correlation function that scales
         distance.
     :type scale: float
     :param nu: The parameter :math:`\\nu` of Matern correlation kernel.
     :type nu: float
     :return: Kernel threshold level
     :rtype: double
     """
     # Number of neighbor points to be correlated in a neighborhood of a point
     adjacency_volume = density * matrix_size
     # If Adjacency is less that one, the correlation matrix becomes identity
     # since no point will be adjacent to other in the correlation matrix.
     if adjacency_volume < 1.0:
         raise ValueError(
                 'Adjacency: %0.2f. Correlation matrix will become identity '
                 % (adjacency_volume) +
                 'since kernel radius is less than grid size. To increase ' +
                 'adjacency, consider increasing density or scale.')
     # Approximate radius of n-sphere containing the above number of adjacent
     # points, assuming adjacent points are distanced on integer lattice.
     adjacency_radius = _ball_radius(adjacency_volume, dimension)
     # Number of points along each axis of the grid
     grid_axis_num_points = matrix_size**(1.0 / dimension)
     # Size of grid elements
     grid_size = 1.0 / (grid_axis_num_points - 1.0)
     # Scale the integer lattice of adjacency radius by the grid size.
     # This is the tapering radius of the kernel
     kernel_radius = grid_size * adjacency_radius
     # Get the kernel functon
     cdef kernel_type kernel_function = get_kernel(kernel)
     # Threshold of kernel to perform tapering
     kernel_threshold = kernel_function(kernel_radius/scale,
                                        kernel_param)
     return kernel_threshold
 # ================
 # estimate max nnz
 # ================
References imate.sample_matrices._sparse_correlation_matrix._ball_radius(), and imate.sample_matrices._kernels.kernel_function.
Referenced by imate.sample_matrices._sparse_correlation_matrix.sparse_correlation_matrix().
_estimate_max_nnz()
def imate.sample_matrices._sparse_correlation_matrix._estimate_max_nnz (matrix_size, dimension, density) private
Estimates the maximum number of nnz needed to store the indices and data of
the generated sparse matrix. Before the generation of the sparse matrix,
its nnz (number of non-zero elements) are not known. Thus, this function
only guesses this value based on its density.
:param matrix_size: The size of the square matrix. This is also the number
    of points used to construct the correlation matrix.
:type matrix_size: int
:param dimension: The dimension of the space of points used to construct
    the correlation matrix.
:type dimension: int
:param sparse_density: The desired density of the sparse matrix. Note that
    the actual density of the generated matrix will not be exactly equal to
    this value. If the matrix size is large, this value is close to the
    actual matrix density.
:type sparse_density: int
:return: maximum non-zero elements of sparse array
:rtype: double
Definition at line 411 of file _sparse_correlation_matrix.pyx.
         density):
     """
     Estimates the maximum number of nnz needed to store the indices and data of
     the generated sparse matrix. Before the generation of the sparse matrix,
     its nnz (number of non-zero elements) are not known. Thus, this function
     only guesses this value based on its density.
     :param matrix_size: The size of the square matrix. This is also the number
         of points used to construct the correlation matrix.
     :type matrix_size: int
     :param dimension: The dimension of the space of points used to construct
         the correlation matrix.
     :type dimension: int
     :param sparse_density: The desired density of the sparse matrix. Note that
         the actual density of the generated matrix will not be exactly equal to
         this value. If the matrix size is large, this value is close to the
         actual matrix density.
     :type sparse_density: int
     :return: maximum non-zero elements of sparse array
     :rtype: double
     """
     estimated_nnz = int(numpy.ceil(density * (matrix_size**2)))
     # Multiply the estimated nnz by unit hypercube over unit ball volume ratio
     safty_coeff = 1.0 / _ball_radius(1.0, dimension)
     max_nnz = int(numpy.ceil(safty_coeff * estimated_nnz))
     return max_nnz
 # =========================
 # sparse correlation matrix
 # =========================
References imate.sample_matrices._sparse_correlation_matrix._ball_radius().
Referenced by imate.sample_matrices._sparse_correlation_matrix.sparse_correlation_matrix().
sparse_correlation_matrix()
def imate.sample_matrices._sparse_correlation_matrix.sparse_correlation_matrix (coords, scale = 0.1, kernel = 'exponential', kernel_param = None, density = 0.001, format = r'csr', dtype = r'float64', verbose = False)
Generates either a sparse correlation matrix.
.. note::
    If the ``kernel_threshold`` is large, it causes:
        * The correlation matrix :math:`\\mathbf{K}` will not be
          positive-definite.
        * The function :math:`\\mathrm{trace}\\left((\\mathbf{K}+t
          \\mathbf{I})^{-1}\\right)` produces unwanted oscillations.
:param coords: 2D array of the coordinates of the set of points. The first
    index of the array is the point Ids and its size determines the size of
    the correlation matrix. The second index of the array corresponds to
    the dimension of the spatial points.
:type coords: numpy.ndarray
:param scale: A parameter of correlation function that scales
    distance.
:type scale: float
:param nu: The parameter :math:`\\nu` of Matern correlation kernel.
:type nu: float
:param density: The desired density of the non-zero elements of the sparse
    matrix. Note that the actual density of the generated matrix may not be
    exactly equal to this value. If the matrix size is large, this value is
    close to the actual matrix density.
:type sparse_density: int
:param verbose: If ``True``, prints some information during the process.
:type verbose: bool
:return: Correlation matrix. If ``coords`` is ``n*m`` array, the
    correlation ``K`` is ``n*n`` matrix.
:rtype: numpy.ndarray or scipy.sparse array
.. warning::
    ``kernel_threshold`` should be large enough so that the correlation
    matrix is not shrunk to identity. If such case happens, this function
    raises a *ValueError* exception.
    In addition, ``kernel_threshold`` should be small enough to not
    eradicate its positive-definiteness. This is not checked by this
    function and the user should be aware of it.
Definition at line 452 of file _sparse_correlation_matrix.pyx.
         verbose=False):
     """
     Generates either a sparse correlation matrix.
     .. note::
         If the ``kernel_threshold`` is large, it causes:
             * The correlation matrix :math:`\\mathbf{K}` will not be
               positive-definite.
             * The function :math:`\\mathrm{trace}\\left((\\mathbf{K}+t
               \\mathbf{I})^{-1}\\right)` produces unwanted oscillations.
     :param coords: 2D array of the coordinates of the set of points. The first
         index of the array is the point Ids and its size determines the size of
         the correlation matrix. The second index of the array corresponds to
         the dimension of the spatial points.
     :type coords: numpy.ndarray
     :param scale: A parameter of correlation function that scales
         distance.
     :type scale: float
     :param nu: The parameter :math:`\\nu` of Matern correlation kernel.
     :type nu: float
     :param density: The desired density of the non-zero elements of the sparse
         matrix. Note that the actual density of the generated matrix may not be
         exactly equal to this value. If the matrix size is large, this value is
         close to the actual matrix density.
     :type sparse_density: int
     :param verbose: If ``True``, prints some information during the process.
     :type verbose: bool
     :return: Correlation matrix. If ``coords`` is ``n*m`` array, the
         correlation ``K`` is ``n*n`` matrix.
     :rtype: numpy.ndarray or scipy.sparse array
     .. warning::
         ``kernel_threshold`` should be large enough so that the correlation
         matrix is not shrunk to identity. If such case happens, this function
         raises a *ValueError* exception.
         In addition, ``kernel_threshold`` should be small enough to not
         eradicate its positive-definiteness. This is not checked by this
         function and the user should be aware of it.
     """
     # Makes kernel paramerter a C-type NAN
     if kernel_param is None:
         kernel_param = NAN
     # size of data and the correlation matrix
     matrix_size = coords.shape[0]
     dimension = coords.shape[1]
     # Get number of CPU threads
     num_threads = multiprocessing.cpu_count()
     # Get the kernel functon
     cdef kernel_type kernel_function = get_kernel(kernel)
     # kernel threshold
     kernel_threshold = _estimate_kernel_threshold(
             matrix_size,
             dimension,
             density,
             scale,
             kernel,
             kernel_param)
     # maximum nnz
     max_nnz = _estimate_max_nnz(
             matrix_size,
             dimension,
             density)
     # Memory view of the correlation matrix
     cdef float[:] mv_matrix_data_float
     cdef double[:] mv_matrix_data_double
     cdef long double[:] mv_matrix_data_long_double
     # C pointer to the correlation matrix
     cdef float* c_matrix_data_float
     cdef double* c_matrix_data_double
     cdef long double* c_matrix_data_long_double
     # Try with the estimated nnz. If not enough, we will double and retry
     success = 0
     while not bool(success):
         # Allocate sparse arrays
         matrix_row_indices = numpy.zeros((max_nnz,), dtype=int)
         matrix_column_indices = numpy.zeros((max_nnz,), dtype=int)
         matrix_data = numpy.zeros((max_nnz,), dtype=dtype)
         nnz = numpy.zeros((1,), dtype=int)
         if dtype == r'float32':
             # Get pointer to the correlation matrix
             mv_matrix_data_float = matrix_data
             c_matrix_data_float = &mv_matrix_data_float[0]
             # Generate matrix assuming the estimated nnz is enough
             success = _generate_matrix[float](
                     coords,
                     matrix_size,
                     dimension,
                     scale,
                     kernel_function,
                     kernel_param,
                     kernel_threshold,
                     num_threads,
                     int(verbose),
                     max_nnz,
                     nnz,
                     matrix_row_indices,
                     matrix_column_indices,
                     c_matrix_data_float)
         elif dtype == r'float64':
             # Get pointer to the correlation matrix
             mv_matrix_data_double = matrix_data
             c_matrix_data_double = &mv_matrix_data_double[0]
             # Generate matrix assuming the estimated nnz is enough
             success = _generate_matrix[double](
                     coords,
                     matrix_size,
                     dimension,
                     scale,
                     kernel_function,
                     kernel_param,
                     kernel_threshold,
                     num_threads,
                     int(verbose),
                     max_nnz,
                     nnz,
                     matrix_row_indices,
                     matrix_column_indices,
                     c_matrix_data_double)
         elif dtype == r'float128':
             # Get pointer to the correlation matrix
             mv_matrix_data_long_double = matrix_data
             c_matrix_data_long_double = &mv_matrix_data_long_double[0]
             # Generate matrix assuming the estimated nnz is enough
             success = _generate_matrix[long_double](
                     coords,
                     matrix_size,
                     dimension,
                     scale,
                     kernel_function,
                     kernel_param,
                     kernel_threshold,
                     num_threads,
                     int(verbose),
                     max_nnz,
                     nnz,
                     matrix_row_indices,
                     matrix_column_indices,
                     c_matrix_data_long_double)
         else:
             raise TypeError('"dtype" should be either "float32", "float64" ' +
                             ', or "float128".')
         # Double the number of pre-allocated nnz and try again
         if not bool(success):
             max_nnz = 2 * max_nnz
             if verbose:
                 print('Retry generation of sparse matrix with max_nnz: %d'
                       % (max_nnz))
     # Construct scipy.sparse.coo_matrix, then convert it to CSR matrix.
     correlation_matrix = scipy.sparse.coo_matrix(
             (matrix_data[:nnz[0]],
              (matrix_row_indices[:nnz[0]],
               matrix_column_indices[:nnz[0]])),
             shape=(matrix_size, matrix_size))
     if format == 'csr':
         correlation_matrix = correlation_matrix.tocsr()
     elif format == 'csc':
         correlation_matrix = correlation_matrix.tocsc()
     else:
         raise ValueError('"format" should be "csr" or "csc".')
     # Actual sparse density
     if verbose:
         actual_density = correlation_matrix.nnz / \
                 numpy.prod(correlation_matrix.shape)
         print('Generated sparse correlation matrix using ' +
               'kernel threshold: %0.4f and ' % (kernel_threshold) +
               'sparse density: %0.2e.' % (actual_density))
     return correlation_matrix
References imate.sample_matrices._sparse_correlation_matrix._estimate_kernel_threshold(), and imate.sample_matrices._sparse_correlation_matrix._estimate_max_nnz().
Variable Documentation
__all__
list imate.sample_matrices._sparse_correlation_matrix.__all__ = ['sparse_correlation_matrix'] private
Definition at line 30 of file _sparse_correlation_matrix.pyx.
chunk_size
int imate.sample_matrices._sparse_correlation_matrix.chunk_size = 1
Definition at line 160 of file _sparse_correlation_matrix.pyx.
chunksize
imate.sample_matrices._sparse_correlation_matrix.chunksize
Definition at line 169 of file _sparse_correlation_matrix.pyx.
matrix_size
imate.sample_matrices._sparse_correlation_matrix.matrix_size
Definition at line 169 of file _sparse_correlation_matrix.pyx.
percent_update
int imate.sample_matrices._sparse_correlation_matrix.percent_update = 20
Definition at line 138 of file _sparse_correlation_matrix.pyx.
progress
int imate.sample_matrices._sparse_correlation_matrix.progress = percent_update * counter[0] // \
Definition at line 237 of file _sparse_correlation_matrix.pyx.
schedule
imate.sample_matrices._sparse_correlation_matrix.schedule
Definition at line 169 of file _sparse_correlation_matrix.pyx.
thread_data
imate.sample_matrices._sparse_correlation_matrix.thread_data
Definition at line 130 of file _sparse_correlation_matrix.pyx.