imate: imate._utilities.plot_utilities Namespace Reference
imate._utilities.plot_utilities Namespace Reference
Functions
def load_plot_settings ()
def save_plot (plt, filename, transparent_background=True, pdf=True, bbox_extra_artists=None, verbose=False)
def show_or_save_plot (plt, filename, transparent_background=True, pdf=True, bbox_extra_artists=None, verbose=False)
Variables
action
module
category
message
Function Documentation
load_plot_settings()
def imate._utilities.plot_utilities.load_plot_settings ()
Specifies general settings for the plots in the example scripts,
namely, it sets plot themes by ``seaborn``, fonts by LaTeX if available.
Definition at line 64 of file plot_utilities.py.
 def load_plot_settings():
     """
     Specifies general settings for the plots in the example scripts,
     namely, it sets plot themes by ``seaborn``, fonts by LaTeX if available.
     """
     # Color palette
     import seaborn as sns
     # sns.set()
     # LaTeX
     if find_executable('latex'):
         try:
             # plt.rc('text',usetex=True)
             matplotlib.rcParams['text.usetex'] = True
             matplotlib.rcParams['text.latex.preamble'] = \
                 r'\usepackage{amsmath}'
             # LaTeX font is a bit small. Increase axes font size
             sns.set(font_scale=1.2)
         except Exception:
             pass
     # Style sheet
     sns.set_style("white")
     sns.set_style("ticks")
     # Font (Note: this should be AFTER the plt.style.use)
     plt.rc('font', family='serif')
     plt.rcParams['svg.fonttype'] = 'none'   # text in svg will be text not path
     # from cycler import cycler
     # matplotlib.rcParams['axes.prop_cycle'] = cycler(color='bgrcmyk')
 # =========
 # save plot
 # =========
Referenced by imate.sample_matrices.correlation_matrix._check_arguments(), imate._trace_estimator.trace_estimator_plot_utilities._plot_error(), imate.interpolator.interpolate_schatten.InterpolateSchatten._plot_finite(), imate._trace_estimator.trace_estimator_plot_utilities._plot_samples(), imate.interpolator.interpolate_schatten.InterpolateSchatten._plot_semi_infinite(), imate.traceinv._hutchinson_method_utilities.check_arguments(), imate._trace_estimator.trace_estimator_utilities.check_arguments(), imate.interpolator.interpolate_logdet.InterpolateLogdet.plot(), imate.interpolator.interpolate_trace.InterpolateTrace.plot(), imate._trace_estimator.trace_estimator_plot_utilities.plot_convergence(), and imate.sample_matrices.correlation_matrix.plot_matrix().
save_plot()
def imate._utilities.plot_utilities.save_plot (plt, filename, transparent_background = True, pdf = True, bbox_extra_artists = None, verbose = False)
Saves plot as svg format in the current working directory.
:param plt: matplotlib.pyplot object for the plots.
:type plt: matplotlib.pyplot
:param filename: Name of the file without extension or directory name.
:type filename: string
:param transparent_background: Sets the background of svg file to be
    transparent.
:type transparent_background: bool
Definition at line 104 of file plot_utilities.py.
         verbose=False):
     """
     Saves plot as svg format in the current working directory.
     :param plt: matplotlib.pyplot object for the plots.
     :type plt: matplotlib.pyplot
     :param filename: Name of the file without extension or directory name.
     :type filename: string
     :param transparent_background: Sets the background of svg file to be
         transparent.
     :type transparent_background: bool
     """
     # Write in the current working directory
     save_dir = os.getcwd()
     # Save plot in svg format
     filename_svg = filename + '.svg'
     filename_pdf = filename + '.pdf'
     if os.access(save_dir, os.W_OK):
         save_fullname_svg = os.path.join(save_dir, filename_svg)
         save_fullname_pdf = os.path.join(save_dir, filename_pdf)
         plt.savefig(
                 save_fullname_svg,
                 transparent=transparent_background,
                 bbox_inches='tight')
         if verbose:
             print('Plot saved to "%s".' % (save_fullname_svg))
         if pdf:
             plt.savefig(
                     save_fullname_pdf,
                     transparent=transparent_background,
                     bbox_extra_artists=bbox_extra_artists, bbox_inches='tight')
             if verbose:
                 print('Plot saved to "%s".' % (save_fullname_pdf))
     else:
         print('Cannot save plot to %s. Directory is not writable.' % save_dir)
 # =================
 # show or save plot
 # =================
Referenced by imate._trace_estimator.trace_estimator_plot_utilities.plot_convergence(), imate.sample_matrices.correlation_matrix.plot_matrix(), and imate._utilities.plot_utilities.show_or_save_plot().
show_or_save_plot()
def imate._utilities.plot_utilities.show_or_save_plot (plt, filename, transparent_background = True, pdf = True, bbox_extra_artists = None, verbose = False)
Shows the plot. If no graphical beckend exists, saves the plot.
Definition at line 157 of file plot_utilities.py.
         verbose=False):
     """
     Shows the plot. If no graphical beckend exists, saves the plot.
     """
     # Check if the graphical back-end exists
     if matplotlib.get_backend() != 'agg' or is_notebook():
         plt.show()
     else:
         # write the plot as SVG file in the current working directory
         save_plot(plt, filename, transparent_background=transparent_background,
                   pdf=pdf, bbox_extra_artists=bbox_extra_artists,
                   verbose=verbose)
References imate._utilities.display_utilities.is_notebook(), and imate._utilities.plot_utilities.save_plot().
Referenced by imate.interpolator.interpolate_schatten.InterpolateSchatten._plot_finite(), imate.interpolator.interpolate_schatten.InterpolateSchatten._plot_semi_infinite(), imate.interpolator.interpolate_logdet.InterpolateLogdet.plot(), and imate.interpolator.interpolate_trace.InterpolateTrace.plot().
Variable Documentation
action
imate._utilities.plot_utilities.action
Definition at line 53 of file plot_utilities.py.
category
imate._utilities.plot_utilities.category
Definition at line 55 of file plot_utilities.py.
message
imate._utilities.plot_utilities.message
Definition at line 56 of file plot_utilities.py.
Referenced by dynamic_loading.load_symbol().
module
imate._utilities.plot_utilities.module
Definition at line 54 of file plot_utilities.py.