{% set name = "imate" %}
{% set data = load_setup_py_data() %}

package:
    name: "{{ name|lower }}"
    version: "{{ data['version'] }}"

source:
    path: ..

# build:
#     number: 0
#     script:
#         - {{ PYTHON }} -m pip install . --single-version-externally-managed --record=record.txt --ignore-installed --no-cache-dir -vvv

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - llvm-openmp  # [osx]

    host:
        - python {{ python }}
        - setuptools
        - scipy>=1.5
        - cython>=0.29,<3.0
        - pip
        - llvm-openmp  # [osx]
    run:
        - python {{ python }}
        - numpy>1.11
        - scipy>=1.5
        - suitesparse
        - matplotlib
        - seaborn
        - llvm-openmp  # [osx]

test:
    imports:
        - imate
    requires:
        - pytest
        - pytest-cov
        - pytest-runner

about:
    home: {{ data['url'] }}
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: {{ data['description'] }}
    description: {{ data['description'] }}
    doc_url: https://ameli.github.io/imate/index.html
    doc_source_url: https://github.com/ameli/imate/blob/main/README.rst
    dev_url: https://github.com/ameli/imate

extra:
    recipe-maintainers:
        - ameli
