imate: Diagonalization< DataType > Class Template Reference
Diagonalization< DataType > Class Template Reference
A static class to find eigenvalues and eigenvectors (diagonalize) tridiagonal and bidiagonal matrices. This class acts as a templated namespace, where all member methods are public and static.
#include <diagonalization.h>
Static Public Member Functions
static int eigh_tridiagonal (DataType *diagonals, DataType *subdiagonals, DataType *eigenvectors, IndexType matrix_size)
Computes all eigenvalues and eigenvectors of a real and symmetric tridiagonal matrix.
static int svd_bidiagonal (DataType *diagonals, DataType *subdiagonals, DataType *U, DataType *Vt, IndexType matrix_size)
Computes all singular-values and left and right eigenvectors of a real and symmetric upper bi-diagonal matrix.
Detailed Description
template<typename DataType>
class Diagonalization< DataType >
A static class to find eigenvalues and eigenvectors (diagonalize) tridiagonal and bidiagonal matrices. This class acts as a templated namespace, where all member methods are public and static.
See also
StochasticLanczosQuadrature
Definition at line 35 of file diagonalization.h.
Member Function Documentation
eigh_tridiagonal()
template<typename DataType > int Diagonalization< DataType >::eigh_tridiagonal (DataType * diagonals, DataType * subdiagonals, DataType * eigenvectors, IndexType matrix_size) static
Computes all eigenvalues and eigenvectors of a real and symmetric tridiagonal matrix.
The symmetric tridiagonal matrix \(\mathbf{A} \) is decomposed in to:
\[ \mathbf{A} = \mathbf{V} \boldsymbol{\Lambda} \mathbf{V}^{\intercal} \]
where \(\mathbf{V} \) is unitary and \(\boldsymbol{\Lambda} \) is diagonal.
Algorithm
This function is equivalent to scipy.linalg.eigh_tridigonal which wraps around LAPACK's sstev and dstev subroutine. Except, this function does not acquire python's GIL, whereas the scipy's function does.
References
Note: Remove blank in the URLs below when opened in the browser.
LAPACK's dstev routine user guide http://www.netlib.org/lapack/explore-html/dc/dd2/group__Da taType_o_t_h_e_reigen_gaaa6df51cfd92c4ab08d41a54bf05c3ab.h tml
Routines for BLAS, LAPACK, MAGMA http://www.icl.utk.edu/~mgates3/docs/lapack.html
Comparison of bdsdc and bdsqr methods http://www.netlib.org/lapack/lug/node53.html
Scipy.linalg.dstev https://docs.scipy.org/doc/scipy/reference/generated/scipy .linalg.lapack.dstev.html
Parameters
[in,out] diagonals A 1D array of the length matrix_size containing the diagonal elements of the matrix. This array will be written in-place with the computed eigenvalues. This array is both input and output of this function.
[in] subdiagonals A 1D array of the length matrix_size-1 containing the sub-diagonal elements of the matrix. This array will be written in-place with intermediate computation values, but is not an output of this function.
[out] eigenvectors 1D array of size matrix_size*matrix_size and represents a 2D array of the shape (matrix_size,matrix_size). The second index of the equivalent 2D array iterates over the column vectors. The array has Fortran ordering, meaning that the first index is contiguous. Thus the i-th element of the j-th vector should be accessed by eigenvectors[j*matrix_size+i]. This array is written in-place and is the output of this function.
[in] matrix_size The size of square matrix.
Returns
The info result of the sstev and dstev subroutine. Zero indicates a successful computation.
Definition at line 90 of file diagonalization.cpp.
 {
     // 'V' computes both eigenvalues and eigenvectors
     char jobz = 'V';
     // Workspace array
     DataType* work = new DataType[2*matrix_size - 2];
     // Leading dimension of 2D eigenvectors array
     int ldz = matrix_size;
     // matrix size
     int n = static_cast<int>(matrix_size);
     // Error code output
     int info;
     // Calling Fortran subroutine
     lapack_xstev(&jobz, &n, diagonals, subdiagonals, eigenvectors, &ldz, work,
               &info);
     delete[] work;
     assert((info == 0, "?stev subroutine returned non-zero status."));
     return info;
 }
References lapack_xstev().
Referenced by cTraceEstimator< DataType >::_c_stochastic_lanczos_quadrature(), and cuTraceEstimator< DataType >::_cu_stochastic_lanczos_quadrature().
svd_bidiagonal()
template<typename DataType > int Diagonalization< DataType >::svd_bidiagonal (DataType * diagonals, DataType * supdiagonals, DataType * U, DataType * Vt, IndexType matrix_size) static
Computes all singular-values and left and right eigenvectors of a real and symmetric upper bi-diagonal matrix.
The symmetric upper bi-diagonal matrix \(\mathbf{A} \) is decomposed in to
\[ \mathbf{A} = \mathbf{U} \boldsymbol{\Sigma} \mathbf{V}^{\intercal} \]
where \(\mathbf{U} \) and \(\mathbf{V} \) are unitary and \(\boldsymbol{\Sigma} \) is diagonal with positive entries.
Algorithm
This function uses LAPACK's dbdsdc Fortran subroutine.
References
Note: Remove blank in the URLs below when opened in the browser.
LAPACK's dbdsdc routine user guide http://www.netlib.org/lapack/explore-html/d9/d08/dbdsdc_8f .html
Routines for BLAS, LAPACK, MAGMA http://www.icl.utk.edu/~mgates3/docs/lapack.html>
Comparison of bdsdc and bdsqr methods http://www.netlib.org/lapack/lug/node53.html
Parameters
[in,out] diagonals A 1D array of the length matrix_size containing the diagonal elements of the matrix. This array will be written in-place with the computed eigenvalues. This array is both input and output of this function.
[in] supdiagonals A 1D array of the length matrix_size-1 containing the sub-diagonal elements of the matrix. This array will be written in-place with intermediate computation values, but is not an output of this function.
[out] U Right eigenvectors represented by 1D array of the length matrix_size*matrix_size which denotes a 2D array of the shape (matrix_size, matrix_size). The second index of the matrix iterates over the column vectors. The array has Fortran ordering, meaning that the first index is contiguous. Thus, the i-th element of the j-th vector should be accessed by U[j*matrix_size+i]. This array is written in place and is the output of this function.
[out] Vt Transpose of left eigenvectors represented by 1D array of the length matrix_size*matrix_size which denotes a 2D array of the shape (matrix_size, matrix_size). The second index of the matrix iterates over the column vectors. The array has Fortran ordering, meaning that the first index is contiguous. Thus, the i-th element of the j-th vector should be accessed by Vt[j*matrix_size+i]. This array is written in place and is the output of this function.
[in] matrix_size The size of square matrix.
Returns
Integer info indicates the status of the computation. Zero indicates a successful computation.
Definition at line 191 of file diagonalization.cpp.
 {
     // Code 'U' indicates the matrix is upper bi-diagonal
     char UPLO = 'U';
     // Code 'I' computes both singular values and singular vectors
     char COMPQ = 'I';
     // matrix size
     int n = static_cast<int>(matrix_size);
     // Leading dimensions of arrays U and Vt
     int LDU = matrix_size;
     int LDVT = matrix_size;
     // There arrays are not referenced when COMPQ is set to 'I'
     DataType* Q = NULL;
     int* IQ = NULL;
     // Work arrays
     DataType* work = new DataType[3*matrix_size*matrix_size + 4*matrix_size];
     int* iwork = new int[8 * matrix_size];
     // Error code output
     int info;
     // Calling Fortran subroutine
     lapack_xbdsdc(&UPLO, &COMPQ, &n, diagonals, supdiagonals, U, &LDU, Vt,
             &LDVT, Q, IQ, work, iwork, &info);
     delete[] work;
     delete[] iwork;
     assert((info == 0, "?stev subroutine returned non-zero status."));
     return info;
 }
References lapack_xbdsdc().
Referenced by cTraceEstimator< DataType >::_c_stochastic_lanczos_quadrature(), and cuTraceEstimator< DataType >::_cu_stochastic_lanczos_quadrature().
The documentation for this class was generated from the following files:
/home/runner/work/imate/imate/imate/_c_trace_estimator/diagonalization.h
/home/runner/work/imate/imate/imate/_c_trace_estimator/diagonalization.cpp