imate: RandomNumberGenerator Class Reference
RandomNumberGenerator Class Reference
Generates 64-bit integers on multiple parallel threads.
#include <random_number_generator.h>
Public Member Functions
RandomNumberGenerator ()
Initializes with one parallel thread.
RandomNumberGenerator (int num_threads_)
Initializes with given number of parallel thread.
~RandomNumberGenerator ()
Deallocates the array of xoshiro_256_star_star.
uint64_t next (int thread_id)
Generates the next random number in the sequence, depending on the thread id.
Protected Member Functions
void initialize (int num_threads_)
Initializes an array of xoshiro_256_star_star objects.
Protected Attributes
int num_threads
Xoshiro256StarStar * xoshiro_256_star_star
Detailed Description
Generates 64-bit integers on multiple parallel threads.
This class creates multiple instances of Xoshiro256StarStar class, with the number of parallel threads. On each thread, it generates random integers independently.
The necessity of using this class is when all threads start at the same time, hence the initial seeds cannot be distinguished using the time() function (since time the same for all threads). Thus the random generator in all threads generate the same senquence of numbers. To avoid this issue, this class jumps the sequence of each instance of Xoshiro256StarStar. Thus, even if their initial state seed is the same, the jump in the state variable makes it different by 2^128 on the sequence.
All member variables of this class aer static and they can be used without declaring an instance of this class. Also, in the same thread, if we call this class from multiple functions, the same sequence if used since the internal state variable is static.
This class can be used by either
Declare a new instance of this class. In this case, the destructor will remove the variables at the end of its lifetime once the last instance of this class goes out of scope.
num_threads = omp_get_num_threads();
// Declare an instance for num_thread parallel threads
RandomNumberGenerator random_number_generator(num_threads);
// Generate random numbers
#pragma omp parallel
{
    int tid = omp_get_thread_num();
    #pragma omp for
    for (int i = 0; i < n; ++i)
    {
        uint64_t a = RandomNumberGenerator::next(tid);
    }
}
// The random_number_generator will go out of scope and it
// automatically deallocate internal static arrays.
Call all functions sttaically. In this case, the internal static arrays should be deallocated manually. Such as
num_threads = omp_get_num_threads();
// Create an internal array of random generator per thread
RandomNumberGenerator::initialize(num_threads);
// Generate random numbers
#pragma omp parallel
{
    int tid = omp_get_thread_num();
    #pragma omp for
    for (int i = 0; i < n; ++i)
    {
        uint64_t a = RandomNumberGenerator::next(tid);
    }
}
// Deallcoate internal static arrays of this class
RandomNumberGenerator::deallocate();
See also
RandomArrayGenerator, Xoshiro256StarStar
Definition at line 103 of file random_number_generator.h.
Constructor & Destructor Documentation
RandomNumberGenerator() [1/2]
RandomNumberGenerator::RandomNumberGenerator ()
Initializes with one parallel thread.
Definition at line 29 of file random_number_generator.cpp.
 {
     int num_threads_ = 1;
     this->initialize(num_threads_);
 }
References initialize().
RandomNumberGenerator() [2/2]
RandomNumberGenerator::RandomNumberGenerator (int num_threads_) explicit
Initializes with given number of parallel thread.
Definition at line 43 of file random_number_generator.cpp.
 {
     this->initialize(num_threads_);
 }
References initialize().
~RandomNumberGenerator()
RandomNumberGenerator::~RandomNumberGenerator ()
Deallocates the array of xoshiro_256_star_star.
Definition at line 56 of file random_number_generator.cpp.
 {
     if (this->xoshiro_256_star_star != NULL)
     {
         delete[] this->xoshiro_256_star_star;
         this->xoshiro_256_star_star = NULL;
     }
 }
References xoshiro_256_star_star.
Member Function Documentation
initialize()
void RandomNumberGenerator::initialize (int num_threads_) protected
Initializes an array of xoshiro_256_star_star objects.
The size of the array is num_threads, corresponding to each parallel thread. Also, the state of the i-th object is jumped (i+1) times so that all random generators have diferent start states. This is the main reason of using this class since it aggregates multiple random generator objects, one for each parallel thread, and all have different initial random state.
Parameters
[in] num_threads_ Number of independent xoshiro_256_star_star objects to be created for each parallel thread.
Definition at line 83 of file random_number_generator.cpp.
 {
     assert(num_threads_ > 0);
     this->num_threads = num_threads_;
     this->xoshiro_256_star_star = new Xoshiro256StarStar[this->num_threads];
     for (int i=0; i < this->num_threads; ++i)
     {
         // Repeate jump j times to have different initial state for each thread
         // This is the main purpose of this class.
         for (int j=0; j < i+1; ++j)
         {
             this->xoshiro_256_star_star[i].jump();
         }
     }
 }
References Xoshiro256StarStar::jump(), num_threads, and xoshiro_256_star_star.
Referenced by RandomNumberGenerator().
next()
uint64_t RandomNumberGenerator::next (int thread_id)
Generates the next random number in the sequence, depending on the thread id.
Parameters
[in] thread_id The thread id of the parallel process.
Definition at line 112 of file random_number_generator.cpp.
 {
     return this->xoshiro_256_star_star[thread_id].next();
 }
References Xoshiro256StarStar::next(), and xoshiro_256_star_star.
Referenced by RandomArrayGenerator< DataType >::generate_random_array().
Member Data Documentation
num_threads
int RandomNumberGenerator::num_threads protected
Definition at line 117 of file random_number_generator.h.
Referenced by initialize().
xoshiro_256_star_star
Xoshiro256StarStar* RandomNumberGenerator::xoshiro_256_star_star protected
Definition at line 118 of file random_number_generator.h.
Referenced by initialize(), next(), and ~RandomNumberGenerator().
The documentation for this class was generated from the following files:
/home/runner/work/imate/imate/imate/_random_generator/random_number_generator.h
/home/runner/work/imate/imate/imate/_random_generator/random_number_generator.cpp