imate: CudaTimer Class Reference
CudaTimer Class Reference
Records elasped time between two CUDA events.
#include <cuda_timer.h>
Public Member Functions
CudaTimer ()
constructor for CudaTimer
~CudaTimer ()
Destructor for CudaTimer.
void start ()
Starts the timer.
void stop ()
Stops the timer.
float elapsed () const
Returns the elapsed time in seconds.
Protected Attributes
cudaEvent_t start_time
cudaEvent_t stop_time
Detailed Description
Records elasped time between two CUDA events.
The measured time is the wall time, not the process time of the GPU. In fact, the measured time the same as the wall clock time of CPU.
Example:
It is better to synchronize all GPU threads before reading the time. For instance:
CudaTimer cuda_timer;
cuda_timer.start();
// Some GPU threads here.
// ...
// Note, this CudaTime measures wall time, so the sleep()
// time counts toward the measured time.
sleep(1);
// Sync threads so the CPU do not jump to the next before
// gpu threads are done.
cudaDeviceSynchronize();
cuda_timer.stop();
float elapsed_time = cuda_timer.elapsed();
See also
Timer
Definition at line 61 of file cuda_timer.h.
Constructor & Destructor Documentation
CudaTimer()
CudaTimer::CudaTimer ()
constructor for CudaTimer
Definition at line 26 of file cuda_timer.cu.
 {
     cudaEventCreate(&this->start_time);
     cudaEventCreate(&this->stop_time);
 }
References cudaEventCreate(), start_time, and stop_time.
~CudaTimer()
CudaTimer::~CudaTimer ()
Destructor for CudaTimer.
Definition at line 40 of file cuda_timer.cu.
 {
     cudaEventDestroy(this->start_time);
     cudaEventDestroy(this->stop_time);
 }
References cudaEventDestroy(), start_time, and stop_time.
Member Function Documentation
elapsed()
float CudaTimer::elapsed () const
Returns the elapsed time in seconds.
Definition at line 80 of file cuda_timer.cu.
 {
     float elapsed_time;
     cudaEventSynchronize(this->stop_time);
     cudaEventElapsedTime(&elapsed_time, this->start_time, this->stop_time);
     // Convert from milli-second to second
     return elapsed_time / 1.0e+3;
 }
References cudaEventElapsedTime(), cudaEventSynchronize(), start_time, and stop_time.
Referenced by cuTraceEstimator< DataType >::cu_trace_estimator().
start()
void CudaTimer::start ()
Starts the timer.
Definition at line 54 of file cuda_timer.cu.
 {
     cudaEventRecord(this->start_time, 0);
 }
References cudaEventRecord(), and start_time.
Referenced by cuTraceEstimator< DataType >::cu_trace_estimator().
stop()
void CudaTimer::stop ()
Stops the timer.
Definition at line 67 of file cuda_timer.cu.
 {
     cudaEventRecord(this->stop_time, 0);
 }
References cudaEventRecord(), and stop_time.
Referenced by cuTraceEstimator< DataType >::cu_trace_estimator().
Member Data Documentation
start_time
cudaEvent_t CudaTimer::start_time protected
Definition at line 72 of file cuda_timer.h.
Referenced by CudaTimer(), elapsed(), start(), and ~CudaTimer().
stop_time
cudaEvent_t CudaTimer::stop_time protected
Definition at line 73 of file cuda_timer.h.
Referenced by CudaTimer(), elapsed(), stop(), and ~CudaTimer().
The documentation for this class was generated from the following files:
/home/runner/work/imate/imate/imate/_cuda_utilities/cuda_timer.h
/home/runner/work/imate/imate/imate/_cuda_utilities/cuda_timer.cu