imate: cDenseMatrix< DataType > Class Template Reference
cDenseMatrix< DataType > Class Template Reference
#include <c_dense_matrix.h>
Public Member Functions
cDenseMatrix ()
cDenseMatrix (const DataType *A_, const LongIndexType num_rows_, const LongIndexType num_columns_, const FlagType A_is_row_major_)
virtual ~cDenseMatrix ()
virtual FlagType is_identity_matrix () const
Checks whether the matrix is identity.
virtual void dot (const DataType *vector, DataType *product)
virtual void dot_plus (const DataType *vector, const DataType alpha, DataType *product)
virtual void transpose_dot (const DataType *vector, DataType *product)
virtual void transpose_dot_plus (const DataType *vector, const DataType alpha, DataType *product)
Public Member Functions inherited from cMatrix< DataType >
cMatrix ()
Default constructor.
virtual ~cMatrix ()
DataType get_eigenvalue (const DataType *known_parameters, const DataType known_eigenvalue, const DataType *inquiry_parameters) const
This virtual function is implemented from its pure virtual function of the base class. In this class, this functio has no use and was only implemented so that this class be able to be instantiated (due to the pure virtual function).
Public Member Functions inherited from cLinearOperator< DataType >
cLinearOperator ()
Default constructor.
cLinearOperator (const LongIndexType num_rows_, const LongIndexType num_columns_)
Constructor with setting num_rows and num_columns.
virtual ~cLinearOperator ()
LongIndexType get_num_rows () const
LongIndexType get_num_columns () const
void set_parameters (DataType *parameters_)
Sets the scalar parameter this->parameters. Parameter is initialized to NULL. However, before calling dot or transpose_dot functions, the parameters must be set.
IndexType get_num_parameters () const
FlagType is_eigenvalue_relation_known () const
Returns a flag that determines whether a relation between the parameters of the operator and its eigenvalue(s) is known.
Protected Attributes
const DataType * A
const FlagType A_is_row_major
Protected Attributes inherited from cLinearOperator< DataType >
const LongIndexType num_rows
const LongIndexType num_columns
FlagType eigenvalue_relation_known
DataType * parameters
IndexType num_parameters
Detailed Description
template<typename DataType>
class cDenseMatrix< DataType >
Definition at line 29 of file c_dense_matrix.h.
Constructor & Destructor Documentation
cDenseMatrix() [1/2]
template<typename DataType > cDenseMatrix< DataType >::cDenseMatrix
Definition at line 26 of file c_dense_matrix.cpp.
                                     :
     A(NULL),
     A_is_row_major(0)
 {
 }
cDenseMatrix() [2/2]
template<typename DataType > cDenseMatrix< DataType >::cDenseMatrix (const DataType * A_, const LongIndexType num_rows_, const LongIndexType num_columns_, const FlagType A_is_row_major_)
Definition at line 38 of file c_dense_matrix.cpp.
                                        :
     // Base class constructor
     cLinearOperator<DataType>(num_rows_, num_columns_),
     // Initializer list
     A(A_),
     A_is_row_major(A_is_row_major_)
 {
 }
~cDenseMatrix()
template<typename DataType > cDenseMatrix< DataType >::~cDenseMatrix virtual
Definition at line 60 of file c_dense_matrix.cpp.
 {
 }
Member Function Documentation
dot()
template<typename DataType > void cDenseMatrix< DataType >::dot (const DataType * vector, DataType * product) virtual
Implements cLinearOperator< DataType >.
Reimplemented in cuDenseMatrix< DataType >.
Definition at line 122 of file c_dense_matrix.cpp.
 {
     cMatrixOperations<DataType>::dense_matvec(
             this->A,
             vector,
             this->num_rows,
             this->num_columns,
             this->A_is_row_major,
             product);
 }
References cMatrixOperations< DataType >::dense_matvec().
dot_plus()
template<typename DataType > void cDenseMatrix< DataType >::dot_plus (const DataType * vector, const DataType alpha, DataType * product) virtual
Implements cMatrix< DataType >.
Reimplemented in cuDenseMatrix< DataType >.
Definition at line 141 of file c_dense_matrix.cpp.
 {
     cMatrixOperations<DataType>::dense_matvec_plus(
             this->A,
             vector,
             alpha,
             this->num_rows,
             this->num_columns,
             this->A_is_row_major,
             product);
 }
References cMatrixOperations< DataType >::dense_matvec_plus().
is_identity_matrix()
template<typename DataType > FlagType cDenseMatrix< DataType >::is_identity_matrix virtual
Checks whether the matrix is identity.
The identity check is primarily performed in the cAffineMatrixFunction class.
Returns
Returns 1 if the input matrix is identity, and 0 otherwise.
See also
cAffineMatrixFunction
Implements cMatrix< DataType >.
Definition at line 79 of file c_dense_matrix.cpp.
 {
     FlagType matrix_is_identity = 1;
     DataType matrix_element;
     // Check matrix element-wise
     for (LongIndexType row=0; row < this->num_rows; ++row)
     {
         for (LongIndexType column=0; column < this-> num_columns; ++column)
         {
             // Get an element of the matrix
             if (this->A_is_row_major)
             {
                 matrix_element = this->A[row * this->num_columns + column];
             }
             else
             {
                 matrix_element = this->A[column * this->num_rows + row];
             }
             // Check the value of element with identity matrix
             if ((row == column) && (matrix_element != 1.0))
             {
                 matrix_is_identity = 0;
                 return matrix_is_identity;
             }
             else if (matrix_element != 0.0)
             {
                 matrix_is_identity = 0;
                 return matrix_is_identity;
             }
         }
     }
     return matrix_is_identity;
 }
transpose_dot()
template<typename DataType > void cDenseMatrix< DataType >::transpose_dot (const DataType * vector, DataType * product) virtual
Implements cLinearOperator< DataType >.
Reimplemented in cuDenseMatrix< DataType >.
Definition at line 162 of file c_dense_matrix.cpp.
 {
     cMatrixOperations<DataType>::dense_transposed_matvec(
             this->A,
             vector,
             this->num_rows,
             this->num_columns,
             this->A_is_row_major,
             product);
 }
References cMatrixOperations< DataType >::dense_transposed_matvec().
transpose_dot_plus()
template<typename DataType > void cDenseMatrix< DataType >::transpose_dot_plus (const DataType * vector, const DataType alpha, DataType * product) virtual
Implements cMatrix< DataType >.
Reimplemented in cuDenseMatrix< DataType >.
Definition at line 181 of file c_dense_matrix.cpp.
 {
     cMatrixOperations<DataType>::dense_transposed_matvec_plus(
             this->A,
             vector,
             alpha,
             this->num_rows,
             this->num_columns,
             this->A_is_row_major,
             product);
 }
References cMatrixOperations< DataType >::dense_transposed_matvec_plus().
Member Data Documentation
A
template<typename DataType > const DataType* cDenseMatrix< DataType >::A protected
Definition at line 67 of file c_dense_matrix.h.
A_is_row_major
template<typename DataType > const FlagType cDenseMatrix< DataType >::A_is_row_major protected
Definition at line 68 of file c_dense_matrix.h.
The documentation for this class was generated from the following files:
/home/runner/work/imate/imate/imate/_c_linear_operator/c_dense_matrix.h
/home/runner/work/imate/imate/imate/_c_linear_operator/c_dense_matrix.cpp