imate: cLinearOperator< DataType > Class Template Reference
cLinearOperator< DataType > Class Template Reference abstract
Base class for linear operators. This class serves as interface for all derived classes.
#include <c_linear_operator.h>
Public Member Functions
cLinearOperator ()
Default constructor.
cLinearOperator (const LongIndexType num_rows_, const LongIndexType num_columns_)
Constructor with setting num_rows and num_columns.
virtual ~cLinearOperator ()
LongIndexType get_num_rows () const
LongIndexType get_num_columns () const
void set_parameters (DataType *parameters_)
Sets the scalar parameter this->parameters. Parameter is initialized to NULL. However, before calling dot or transpose_dot functions, the parameters must be set.
IndexType get_num_parameters () const
FlagType is_eigenvalue_relation_known () const
Returns a flag that determines whether a relation between the parameters of the operator and its eigenvalue(s) is known.
virtual DataType get_eigenvalue (const DataType *known_parameters, const DataType known_eigenvalue, const DataType *inquiry_parameters) const =0
virtual void dot (const DataType *vector, DataType *product)=0
virtual void transpose_dot (const DataType *vector, DataType *product)=0
Protected Attributes
const LongIndexType num_rows
const LongIndexType num_columns
FlagType eigenvalue_relation_known
DataType * parameters
IndexType num_parameters
Detailed Description
template<typename DataType>
class cLinearOperator< DataType >
Base class for linear operators. This class serves as interface for all derived classes.
The prefix c in this class's name (and its derivatves), stands for the cpp code, intrast to the cu prefix, which stands for the cuda code. Most derived classes have a cuda counterpart.
See also
cMatrix, cAffineMatrixFunction, cuLinearOperator
Definition at line 40 of file c_linear_operator.h.
Constructor & Destructor Documentation
cLinearOperator() [1/2]
template<typename DataType > cLinearOperator< DataType >::cLinearOperator
Default constructor.
Definition at line 28 of file c_linear_operator.cpp.
                                           :
     num_rows(0),
     num_columns(0),
     eigenvalue_relation_known(0),
     parameters(NULL),
     num_parameters(0)
 {
 }
cLinearOperator() [2/2]
template<typename DataType > cLinearOperator< DataType >::cLinearOperator (const LongIndexType num_rows_, const LongIndexType num_columns_)
Constructor with setting num_rows and num_columns.
Note
For the classed that are virtually derived (virtual inheritance) from this class, this constructor will never be called. Rather, the default constructor is called by the most derived class. Thus, set the member data directly instead of below.
Definition at line 50 of file c_linear_operator.cpp.
                                          :
     // Initializer list
     num_rows(num_rows_),
     num_columns(num_columns_),
     eigenvalue_relation_known(0),
     parameters(NULL),
     num_parameters(0)
 {
 }
~cLinearOperator()
template<typename DataType > cLinearOperator< DataType >::~cLinearOperator virtual
Definition at line 69 of file c_linear_operator.cpp.
 {
 }
Member Function Documentation
dot()
template<typename DataType > virtual void cLinearOperator< DataType >::dot (const DataType * vector, DataType * product) pure virtual
Implemented in cuDenseAffineMatrixFunction< DataType >, cuCSRAffineMatrixFunction< DataType >, cuCSCAffineMatrixFunction< DataType >, cDenseMatrix< DataType >, cDenseAffineMatrixFunction< DataType >, cCSRMatrix< DataType >, cCSRAffineMatrixFunction< DataType >, cCSCMatrix< DataType >, cCSCAffineMatrixFunction< DataType >, cuDenseMatrix< DataType >, cuCSRMatrix< DataType >, and cuCSCMatrix< DataType >.
Referenced by c_golub_kahn_bidiagonalization(), c_lanczos_tridiagonalization(), cu_golub_kahn_bidiagonalization(), and cu_lanczos_tridiagonalization().
get_eigenvalue()
template<typename DataType > virtual DataType cLinearOperator< DataType >::get_eigenvalue (const DataType * known_parameters, const DataType known_eigenvalue, const DataType * inquiry_parameters) const pure virtual
Implemented in cuAffineMatrixFunction< DataType >, cMatrix< DataType >, and cAffineMatrixFunction< DataType >.
Referenced by cTraceEstimator< DataType >::_c_stochastic_lanczos_quadrature(), and cuTraceEstimator< DataType >::_cu_stochastic_lanczos_quadrature().
get_num_columns()
template<typename DataType > LongIndexType cLinearOperator< DataType >::get_num_columns
Definition at line 90 of file c_linear_operator.cpp.
 {
     return this->num_columns;
 }
get_num_parameters()
template<typename DataType > IndexType cLinearOperator< DataType >::get_num_parameters
Definition at line 119 of file c_linear_operator.cpp.
 {
     return this->num_parameters;
 }
Referenced by cTraceEstimator< DataType >::_c_stochastic_lanczos_quadrature(), and cuTraceEstimator< DataType >::_cu_stochastic_lanczos_quadrature().
get_num_rows()
template<typename DataType > LongIndexType cLinearOperator< DataType >::get_num_rows
Definition at line 79 of file c_linear_operator.cpp.
 {
     return this->num_rows;
 }
Referenced by cTraceEstimator< DataType >::_c_stochastic_lanczos_quadrature(), cuTraceEstimator< DataType >::_cu_stochastic_lanczos_quadrature(), cTraceEstimator< DataType >::c_trace_estimator(), and cuTraceEstimator< DataType >::cu_trace_estimator().
is_eigenvalue_relation_known()
template<typename DataType > FlagType cLinearOperator< DataType >::is_eigenvalue_relation_known
Returns a flag that determines whether a relation between the parameters of the operator and its eigenvalue(s) is known.
Returns
If the relation between parameters and eigenvalue of the operator is known, returns 1, otherwise returns 0.
Definition at line 136 of file c_linear_operator.cpp.
 {
     return this->eigenvalue_relation_known;
 }
Referenced by cTraceEstimator< DataType >::_c_stochastic_lanczos_quadrature(), and cuTraceEstimator< DataType >::_cu_stochastic_lanczos_quadrature().
set_parameters()
template<typename DataType > void cLinearOperator< DataType >::set_parameters (DataType * parameters_)
Sets the scalar parameter this->parameters. Parameter is initialized to NULL. However, before calling dot or transpose_dot functions, the parameters must be set.
Parameters
[in] parameters_ A pointer to the scalar or array of parameters.
Definition at line 108 of file c_linear_operator.cpp.
 {
     this->parameters = parameters_;
 }
Referenced by cTraceEstimator< DataType >::_c_stochastic_lanczos_quadrature(), and cuTraceEstimator< DataType >::_cu_stochastic_lanczos_quadrature().
transpose_dot()
template<typename DataType > virtual void cLinearOperator< DataType >::transpose_dot (const DataType * vector, DataType * product) pure virtual
Implemented in cuDenseAffineMatrixFunction< DataType >, cuCSRAffineMatrixFunction< DataType >, cuCSCAffineMatrixFunction< DataType >, cDenseMatrix< DataType >, cDenseAffineMatrixFunction< DataType >, cCSRMatrix< DataType >, cCSRAffineMatrixFunction< DataType >, cCSCMatrix< DataType >, cCSCAffineMatrixFunction< DataType >, cuDenseMatrix< DataType >, cuCSRMatrix< DataType >, and cuCSCMatrix< DataType >.
Referenced by c_golub_kahn_bidiagonalization(), and cu_golub_kahn_bidiagonalization().
Member Data Documentation
eigenvalue_relation_known
template<typename DataType > FlagType cLinearOperator< DataType >::eigenvalue_relation_known protected
Definition at line 77 of file c_linear_operator.h.
Referenced by cCSCAffineMatrixFunction< DataType >::cCSCAffineMatrixFunction(), cCSRAffineMatrixFunction< DataType >::cCSRAffineMatrixFunction(), cDenseAffineMatrixFunction< DataType >::cDenseAffineMatrixFunction(), cuCSCAffineMatrixFunction< DataType >::cuCSCAffineMatrixFunction(), cuCSRAffineMatrixFunction< DataType >::cuCSRAffineMatrixFunction(), and cuDenseAffineMatrixFunction< DataType >::cuDenseAffineMatrixFunction().
num_columns
template<typename DataType > const LongIndexType cLinearOperator< DataType >::num_columns protected
Definition at line 76 of file c_linear_operator.h.
num_parameters
template<typename DataType > IndexType cLinearOperator< DataType >::num_parameters protected
Definition at line 79 of file c_linear_operator.h.
Referenced by cAffineMatrixFunction< DataType >::cAffineMatrixFunction(), and cuAffineMatrixFunction< DataType >::cuAffineMatrixFunction().
num_rows
template<typename DataType > const LongIndexType cLinearOperator< DataType >::num_rows protected
Definition at line 75 of file c_linear_operator.h.
parameters
template<typename DataType > DataType* cLinearOperator< DataType >::parameters protected
Definition at line 78 of file c_linear_operator.h.
The documentation for this class was generated from the following files:
/home/runner/work/imate/imate/imate/_c_linear_operator/c_linear_operator.h
/home/runner/work/imate/imate/imate/_c_linear_operator/c_linear_operator.cpp