imate: cCSCMatrix< DataType > Class Template Reference
cCSCMatrix< DataType > Class Template Reference
#include <c_csc_matrix.h>
Public Member Functions
cCSCMatrix ()
cCSCMatrix (const DataType *A_data_, const LongIndexType *A_indices_, const LongIndexType *A_index_pointer_, const LongIndexType num_rows_, const LongIndexType num_columns_)
virtual ~cCSCMatrix ()
virtual FlagType is_identity_matrix () const
Checks whether the matrix is identity.
LongIndexType get_nnz () const
Returns the number of non-zero elements of the sparse matrix.
virtual void dot (const DataType *vector, DataType *product)
virtual void dot_plus (const DataType *vector, const DataType alpha, DataType *product)
virtual void transpose_dot (const DataType *vector, DataType *product)
virtual void transpose_dot_plus (const DataType *vector, const DataType alpha, DataType *product)
Public Member Functions inherited from cMatrix< DataType >
cMatrix ()
Default constructor.
virtual ~cMatrix ()
DataType get_eigenvalue (const DataType *known_parameters, const DataType known_eigenvalue, const DataType *inquiry_parameters) const
This virtual function is implemented from its pure virtual function of the base class. In this class, this functio has no use and was only implemented so that this class be able to be instantiated (due to the pure virtual function).
Public Member Functions inherited from cLinearOperator< DataType >
cLinearOperator ()
Default constructor.
cLinearOperator (const LongIndexType num_rows_, const LongIndexType num_columns_)
Constructor with setting num_rows and num_columns.
virtual ~cLinearOperator ()
LongIndexType get_num_rows () const
LongIndexType get_num_columns () const
void set_parameters (DataType *parameters_)
Sets the scalar parameter this->parameters. Parameter is initialized to NULL. However, before calling dot or transpose_dot functions, the parameters must be set.
IndexType get_num_parameters () const
FlagType is_eigenvalue_relation_known () const
Returns a flag that determines whether a relation between the parameters of the operator and its eigenvalue(s) is known.
Protected Attributes
const DataType * A_data
const LongIndexType * A_indices
const LongIndexType * A_index_pointer
Protected Attributes inherited from cLinearOperator< DataType >
const LongIndexType num_rows
const LongIndexType num_columns
FlagType eigenvalue_relation_known
DataType * parameters
IndexType num_parameters
Detailed Description
template<typename DataType>
class cCSCMatrix< DataType >
Definition at line 29 of file c_csc_matrix.h.
Constructor & Destructor Documentation
cCSCMatrix() [1/2]
template<typename DataType > cCSCMatrix< DataType >::cCSCMatrix
Definition at line 26 of file c_csc_matrix.cpp.
                                 :
     A_data(NULL),
     A_indices(NULL),
     A_index_pointer(NULL)
 {
 }
cCSCMatrix() [2/2]
template<typename DataType > cCSCMatrix< DataType >::cCSCMatrix (const DataType * A_data_, const LongIndexType * A_indices_, const LongIndexType * A_index_pointer_, const LongIndexType num_rows_, const LongIndexType num_columns_)
Definition at line 39 of file c_csc_matrix.cpp.
                                          :
     // Base class constructor
     cLinearOperator<DataType>(num_rows_, num_columns_),
     // Initializer list
     A_data(A_data_),
     A_indices(A_indices_),
     A_index_pointer(A_index_pointer_)
 {
 }
~cCSCMatrix()
template<typename DataType > cCSCMatrix< DataType >::~cCSCMatrix virtual
Definition at line 62 of file c_csc_matrix.cpp.
 {
 }
Member Function Documentation
dot()
template<typename DataType > void cCSCMatrix< DataType >::dot (const DataType * vector, DataType * product) virtual
Implements cLinearOperator< DataType >.
Reimplemented in cuCSCMatrix< DataType >.
Definition at line 139 of file c_csc_matrix.cpp.
 {
     cMatrixOperations<DataType>::csc_matvec(
             this->A_data,
             this->A_indices,
             this->A_index_pointer,
             vector,
             this->num_rows,
             this->num_columns,
             product);
 }
References cMatrixOperations< DataType >::csc_matvec().
dot_plus()
template<typename DataType > void cCSCMatrix< DataType >::dot_plus (const DataType * vector, const DataType alpha, DataType * product) virtual
Implements cMatrix< DataType >.
Reimplemented in cuCSCMatrix< DataType >.
Definition at line 159 of file c_csc_matrix.cpp.
 {
     cMatrixOperations<DataType>::csc_matvec_plus(
             this->A_data,
             this->A_indices,
             this->A_index_pointer,
             vector,
             alpha,
             this->num_columns,
             product);
 }
References cMatrixOperations< DataType >::csc_matvec_plus().
get_nnz()
template<typename DataType > LongIndexType cCSCMatrix< DataType >::get_nnz
Returns the number of non-zero elements of the sparse matrix.
The nnz of a CSC matrix can be obtained from the last element of A_index_pointer. The size of array A_index_pointer is one plus the number of columns of the matrix.
Returns
The nnz of the matrix.
Definition at line 128 of file c_csc_matrix.cpp.
 {
     return this->A_index_pointer[this->num_columns];
 }
is_identity_matrix()
template<typename DataType > FlagType cCSCMatrix< DataType >::is_identity_matrix virtual
Checks whether the matrix is identity.
The identity check is primarily performed in the cAffineMatrixFunction class.
Returns
Returns 1 if the input matrix is identity, and 0 otherwise.
See also
cAffineMatrixFunction
Implements cMatrix< DataType >.
Definition at line 81 of file c_csc_matrix.cpp.
 {
     FlagType matrix_is_identity = 1;
     LongIndexType index_pointer;
     LongIndexType row;
     // Check matrix element-wise
     for (LongIndexType column=0; column < this->num_columns; ++column)
     {
         for (index_pointer=this->A_index_pointer[column];
              index_pointer < this->A_index_pointer[column+1];
              ++index_pointer)
         {
             row = this->A_indices[index_pointer];
             if ((row == column) && \
                (this->A_data[index_pointer] != 1.0))
             {
                 matrix_is_identity = 0;
                 return matrix_is_identity;
             }
             else if (this->A_data[index_pointer] != 0.0)
             {
                 matrix_is_identity = 0;
                 return matrix_is_identity;
             }
         }
     }
     return matrix_is_identity;
 }
transpose_dot()
template<typename DataType > void cCSCMatrix< DataType >::transpose_dot (const DataType * vector, DataType * product) virtual
Implements cLinearOperator< DataType >.
Reimplemented in cuCSCMatrix< DataType >.
Definition at line 180 of file c_csc_matrix.cpp.
 {
     cMatrixOperations<DataType>::csc_transposed_matvec(
             this->A_data,
             this->A_indices,
             this->A_index_pointer,
             vector,
             this->num_columns,
             product);
 }
References cMatrixOperations< DataType >::csc_transposed_matvec().
transpose_dot_plus()
template<typename DataType > void cCSCMatrix< DataType >::transpose_dot_plus (const DataType * vector, const DataType alpha, DataType * product) virtual
Implements cMatrix< DataType >.
Reimplemented in cuCSCMatrix< DataType >.
Definition at line 199 of file c_csc_matrix.cpp.
 {
     cMatrixOperations<DataType>::csc_transposed_matvec_plus(
             this->A_data,
             this->A_indices,
             this->A_index_pointer,
             vector,
             alpha,
             this->num_columns,
             product);
 }
References cMatrixOperations< DataType >::csc_transposed_matvec_plus().
Member Data Documentation
A_data
template<typename DataType > const DataType* cCSCMatrix< DataType >::A_data protected
Definition at line 70 of file c_csc_matrix.h.
A_index_pointer
template<typename DataType > const LongIndexType* cCSCMatrix< DataType >::A_index_pointer protected
Definition at line 72 of file c_csc_matrix.h.
A_indices
template<typename DataType > const LongIndexType* cCSCMatrix< DataType >::A_indices protected
Definition at line 71 of file c_csc_matrix.h.
The documentation for this class was generated from the following files:
/home/runner/work/imate/imate/imate/_c_linear_operator/c_csc_matrix.h
/home/runner/work/imate/imate/imate/_c_linear_operator/c_csc_matrix.cpp