imate: CudaInterface< ArrayType > Class Template Reference
CudaInterface< ArrayType > Class Template Reference
An interface to CUDA linrary to facilitate working with CUDA, such as memory allocation, copy data to and from device, etc. This class contains all public static functions and serves as a namespace.
#include <cuda_interface.h>
Static Public Member Functions
static ArrayType * alloc (const LongIndexType array_size)
Allocates memory on gpu device. This function creates a pointer and returns it.
static void alloc (ArrayType *&device_array, const LongIndexType array_size)
Allocates memory on gpu device. This function uses an existing given pointer.
static void alloc_bytes (void *&device_array, const size_t num_bytes)
Allocates memory on gpu device. This function uses an existing given pointer.
static void copy_to_device (const ArrayType *host_array, const LongIndexType array_size, ArrayType *device_array)
Copies memory on host to device memory.
static void del (void *device_array)
Deletes memory on gpu device if its pointer is not NULL, then sets the pointer to NULL.
static void set_device (int device_id)
Sets the current device in multi-gpu applications.
static int get_device ()
Gets the current device in multi-gpu applications.
Detailed Description
template<typename ArrayType>
class CudaInterface< ArrayType >
An interface to CUDA linrary to facilitate working with CUDA, such as memory allocation, copy data to and from device, etc. This class contains all public static functions and serves as a namespace.
Definition at line 36 of file cuda_interface.h.
Member Function Documentation
alloc() [1/2]
template<typename ArrayType > void CudaInterface< ArrayType >::alloc (ArrayType *& device_array, const LongIndexType array_size) static
Allocates memory on gpu device. This function uses an existing given pointer.
Parameters
[in,out] device_array A pointer to the device memory to be allocated
[in] array_size Size of the array to be allocated.
Definition at line 76 of file cuda_interface.cu.
 {
     // Check if overflowing might make array_size negative if LongIndexType is
     // a signed type. For unsigned type, we have no clue at this point.
     assert(array_size > 0);
     // Check if computing num_bytes will not overflow size_t (unsigned int)
     size_t max_index = std::numeric_limits<size_t>::max();
     if (max_index / sizeof(ArrayType) < array_size)
     {
         std::cerr << "The size of array in bytes exceeds the maximum " \
                   << "integer limit, which is: " << max_index << ". The " \
                   << "array size is: " << array_size << ", and the size of " \
                   << "data type is: " << sizeof(ArrayType) << "-bytes." \
                   << std::endl;
         abort();
     }
     size_t num_bytes = static_cast<size_t>(array_size) * sizeof(ArrayType);
     cudaError_t error = cudaMalloc(&device_array, num_bytes);
     assert(error == cudaSuccess);
 }
References cudaMalloc().
alloc() [2/2]
template<typename ArrayType > ArrayType * CudaInterface< ArrayType >::alloc (const LongIndexType array_size) static
Allocates memory on gpu device. This function creates a pointer and returns it.
Parameters
[in] array_size Size of the array to be allocated.
Returns
A pointer to the allocated 1D array on device.
Definition at line 36 of file cuda_interface.cu.
 {
     // Check if overflowing might make array_size negative if LongIndexType is
     // a signed type. For unsigned type, we have no clue at this point.
     assert(array_size > 0);
     // Check if computing num_bytes will not overflow size_t (unsigned int)
     size_t max_index = std::numeric_limits<size_t>::max();
     if (max_index / sizeof(ArrayType) < array_size)
     {
         std::cerr << "The size of array in bytes exceeds the maximum " \
                   << "integer limit, which is: " << max_index << ". The " \
                   << "array size is: " << array_size << ", and the size of " \
                   << "data type is: " << sizeof(ArrayType) << "-bytes." \
                   << std::endl;
         abort();
     }
     ArrayType* device_array;
     size_t num_bytes = static_cast<size_t>(array_size) * sizeof(ArrayType);
     cudaError_t error = cudaMalloc(&device_array, num_bytes);
     assert(error == cudaSuccess);
     return device_array;
 }
References cudaMalloc().
Referenced by cuCSCMatrix< DataType >::copy_host_to_device(), cuCSRMatrix< DataType >::copy_host_to_device(), cuDenseMatrix< DataType >::copy_host_to_device(), cu_golub_kahn_bidiagonalization(), and cu_lanczos_tridiagonalization().
alloc_bytes()
template<typename ArrayType > void CudaInterface< ArrayType >::alloc_bytes (void *& device_array, const size_t num_bytes) static
Allocates memory on gpu device. This function uses an existing given pointer.
Parameters
[in,out] device_array A pointer to the device memory to be allocated
[in] num_bytes Number of bytes of the array to be allocated.
Definition at line 115 of file cuda_interface.cu.
 {
     // Check if overflowing might make num_bytes negative if size_t is
     // a signed type. For unsigned type, we have no clue at this point.
     assert(num_bytes > 0);
     cudaError_t error = cudaMalloc(&device_array, num_bytes);
     assert(error == cudaSuccess);
 }
References cudaMalloc().
Referenced by cuCSCMatrix< DataType >::allocate_buffer(), and cuCSRMatrix< DataType >::allocate_buffer().
copy_to_device()
template<typename ArrayType > void CudaInterface< ArrayType >::copy_to_device (const ArrayType * host_array, const LongIndexType array_size, ArrayType * device_array) static
Copies memory on host to device memory.
Parameters
[in] host_array Pointer of 1D array memory on host
[in] array_size The size of array on host.
[out] device_array Pointer to the destination memory on device.
Definition at line 142 of file cuda_interface.cu.
 {
     size_t num_bytes = static_cast<size_t>(array_size) * sizeof(ArrayType);
     cudaError_t error = cudaMemcpy(device_array, host_array, num_bytes,
                                    cudaMemcpyHostToDevice);
     assert(error == cudaSuccess);
 }
References cudaMemcpy().
Referenced by cuCSCMatrix< DataType >::copy_host_to_device(), cuCSRMatrix< DataType >::copy_host_to_device(), cuDenseMatrix< DataType >::copy_host_to_device(), cu_golub_kahn_bidiagonalization(), cu_lanczos_tridiagonalization(), and cuOrthogonalization< DataType >::orthogonalize_vectors().
del()
template<typename ArrayType > void CudaInterface< ArrayType >::del (void * device_array) static
Deletes memory on gpu device if its pointer is not NULL, then sets the pointer to NULL.
Parameters
[in,out] device_array A pointer to memory on device to be deleted. This pointer will be set to NULL.
Definition at line 166 of file cuda_interface.cu.
 {
     if (device_array != NULL)
     {
         cudaError_t error = cudaFree(device_array);
         assert(error == cudaSuccess);
         device_array = NULL;
     }
 }
References cudaFree().
Referenced by cuCSCMatrix< DataType >::allocate_buffer(), cuCSRMatrix< DataType >::allocate_buffer(), cu_golub_kahn_bidiagonalization(), cu_lanczos_tridiagonalization(), cuCSCMatrix< DataType >::~cuCSCMatrix(), cuCSRMatrix< DataType >::~cuCSRMatrix(), and cuDenseMatrix< DataType >::~cuDenseMatrix().
get_device()
template<typename ArrayType > int CudaInterface< ArrayType >::get_device static
Gets the current device in multi-gpu applications.
Returns
device_id The id of the current device. The id is a number from 0 to num_gpu_devices-1
Definition at line 206 of file cuda_interface.cu.
 {
     int device_id = -1;
     cudaError_t error = cudaGetDevice(&device_id);
     assert(error == cudaSuccess);
     return device_id;
 }
References cudaGetDevice().
Referenced by cuAffineMatrixFunction< DataType >::_add_scaled_vector(), cuCSCMatrix< DataType >::dot(), cuCSRMatrix< DataType >::dot(), cuDenseMatrix< DataType >::dot(), cuCSCMatrix< DataType >::dot_plus(), cuCSRMatrix< DataType >::dot_plus(), cuDenseMatrix< DataType >::dot_plus(), cuLinearOperator< DataType >::get_cublas_handle(), cuCSCMatrix< DataType >::transpose_dot(), cuCSRMatrix< DataType >::transpose_dot(), cuDenseMatrix< DataType >::transpose_dot(), cuCSCMatrix< DataType >::transpose_dot_plus(), cuCSRMatrix< DataType >::transpose_dot_plus(), and cuDenseMatrix< DataType >::transpose_dot_plus().
set_device()
template<typename ArrayType > void CudaInterface< ArrayType >::set_device (int device_id) static
Sets the current device in multi-gpu applications.
Parameters
[in] device_id The id of the device to switch to. The id is a number from 0 to num_gpu_devices-1
Definition at line 188 of file cuda_interface.cu.
 {
     cudaError_t error = cudaSetDevice(device_id);
     assert(error == cudaSuccess);
 }
References cudaSetDevice().
Referenced by cuCSCMatrix< DataType >::copy_host_to_device(), cuCSRMatrix< DataType >::copy_host_to_device(), cuDenseMatrix< DataType >::copy_host_to_device(), cuTraceEstimator< DataType >::cu_trace_estimator(), cuLinearOperator< DataType >::initialize_cublas_handle(), cuLinearOperator< DataType >::initialize_cusparse_handle(), cuCSCMatrix< DataType >::~cuCSCMatrix(), cuCSRMatrix< DataType >::~cuCSRMatrix(), cuDenseMatrix< DataType >::~cuDenseMatrix(), and cuLinearOperator< DataType >::~cuLinearOperator().
The documentation for this class was generated from the following files:
/home/runner/work/imate/imate/imate/_cuda_utilities/cuda_interface.h
/home/runner/work/imate/imate/imate/_cuda_utilities/cuda_interface.cu