imate: cuDenseMatrix< DataType > Class Template Reference
cuDenseMatrix< DataType > Class Template Reference
#include <cu_dense_matrix.h>
Public Member Functions
cuDenseMatrix ()
cuDenseMatrix (const DataType *A_, const LongIndexType num_rows_, const LongIndexType num_columns_, const FlagType A_is_row_major_, const int num_gpu_devices_)
virtual ~cuDenseMatrix ()
virtual void dot (const DataType *device_vector, DataType *device_product)
virtual void dot_plus (const DataType *device_vector, const DataType alpha, DataType *device_product)
virtual void transpose_dot (const DataType *device_vector, DataType *device_product)
virtual void transpose_dot_plus (const DataType *device_vector, const DataType alpha, DataType *device_product)
Public Member Functions inherited from cuMatrix< DataType >
cuMatrix ()
cuMatrix (int num_gpu_devices_)
virtual ~cuMatrix ()
Public Member Functions inherited from cuLinearOperator< DataType >
cuLinearOperator ()
cuLinearOperator (int num_gpu_devices_)
Constructor with setting num_rows and num_columns.
virtual ~cuLinearOperator ()
cublasHandle_t get_cublas_handle () const
This function returns a reference to the cublasHandle_t object. The object will be created, if it is not created already.
Public Member Functions inherited from cLinearOperator< DataType >
cLinearOperator ()
Default constructor.
cLinearOperator (const LongIndexType num_rows_, const LongIndexType num_columns_)
Constructor with setting num_rows and num_columns.
virtual ~cLinearOperator ()
LongIndexType get_num_rows () const
LongIndexType get_num_columns () const
void set_parameters (DataType *parameters_)
Sets the scalar parameter this->parameters. Parameter is initialized to NULL. However, before calling dot or transpose_dot functions, the parameters must be set.
IndexType get_num_parameters () const
FlagType is_eigenvalue_relation_known () const
Returns a flag that determines whether a relation between the parameters of the operator and its eigenvalue(s) is known.
Public Member Functions inherited from cDenseMatrix< DataType >
cDenseMatrix ()
cDenseMatrix (const DataType *A_, const LongIndexType num_rows_, const LongIndexType num_columns_, const FlagType A_is_row_major_)
virtual ~cDenseMatrix ()
virtual FlagType is_identity_matrix () const
Checks whether the matrix is identity.
Public Member Functions inherited from cMatrix< DataType >
cMatrix ()
Default constructor.
virtual ~cMatrix ()
DataType get_eigenvalue (const DataType *known_parameters, const DataType known_eigenvalue, const DataType *inquiry_parameters) const
This virtual function is implemented from its pure virtual function of the base class. In this class, this functio has no use and was only implemented so that this class be able to be instantiated (due to the pure virtual function).
Protected Member Functions
virtual void copy_host_to_device ()
Copies the member data from the host memory to the device memory.
Protected Member Functions inherited from cuLinearOperator< DataType >
int query_gpu_devices () const
Before any numerical computation, this method chechs if any gpu device is available on the machine, or notifies the user if nothing was found.
void initialize_cublas_handle ()
Creates a cublasHandle_t object, if not created already.
void initialize_cusparse_handle ()
Creates a cusparseHandle_t object, if not created already.
Protected Attributes
DataType ** device_A
Protected Attributes inherited from cuLinearOperator< DataType >
int num_gpu_devices
bool copied_host_to_device
cublasHandle_t * cublas_handle
cusparseHandle_t * cusparse_handle
Protected Attributes inherited from cLinearOperator< DataType >
const LongIndexType num_rows
const LongIndexType num_columns
FlagType eigenvalue_relation_known
DataType * parameters
IndexType num_parameters
Protected Attributes inherited from cDenseMatrix< DataType >
const DataType * A
const FlagType A_is_row_major
Detailed Description
template<typename DataType>
class cuDenseMatrix< DataType >
Definition at line 30 of file cu_dense_matrix.h.
Constructor & Destructor Documentation
cuDenseMatrix() [1/2]
template<typename DataType > cuDenseMatrix< DataType >::cuDenseMatrix
Definition at line 29 of file cu_dense_matrix.cu.
                                       :
     device_A(NULL)
 {
 }
cuDenseMatrix() [2/2]
template<typename DataType > cuDenseMatrix< DataType >::cuDenseMatrix (const DataType * A_, const LongIndexType num_rows_, const LongIndexType num_columns_, const FlagType A_is_row_major_, const int num_gpu_devices_)
Definition at line 40 of file cu_dense_matrix.cu.
                                    :
     // Base class constructor
     cLinearOperator<DataType>(num_rows_, num_columns_),
     cDenseMatrix<DataType>(A_, num_rows_, num_columns_, A_is_row_major_),
     cuMatrix<DataType>(num_gpu_devices_),
     // Initializer list
     device_A(NULL)
 {
     this->initialize_cublas_handle();
     this->copy_host_to_device();
 }
References cuDenseMatrix< DataType >::copy_host_to_device(), and cuLinearOperator< DataType >::initialize_cublas_handle().
~cuDenseMatrix()
template<typename DataType > cuDenseMatrix< DataType >::~cuDenseMatrix virtual
Definition at line 66 of file cu_dense_matrix.cu.
 {
     // Member objects exist if the second constructor was called.
     if (this->copied_host_to_device)
     {
         // Deallocate arrays of data on gpu
         for (int device_id = 0; device_id < this->num_gpu_devices; ++device_id)
         {
             // Switch to a device
             CudaInterface<DataType>::set_device(device_id);
             // Deallocate
             CudaInterface<DataType>::del(this->device_A[device_id]);
         }
         delete[] this->device_A;
         this->device_A = NULL;
     }
 }
References CudaInterface< ArrayType >::del(), and CudaInterface< ArrayType >::set_device().
Member Function Documentation
copy_host_to_device()
template<typename DataType > void cuDenseMatrix< DataType >::copy_host_to_device protected virtual
Copies the member data from the host memory to the device memory.
Implements cuMatrix< DataType >.
Definition at line 95 of file cu_dense_matrix.cu.
 {
     if (!this->copied_host_to_device)
     {
         // Set the number of threads
         omp_set_num_threads(this->num_gpu_devices);
         // Create array of pointers for data on each gpu device
         this->device_A = new DataType*[this->num_gpu_devices];
         // Size of data
         LongIndexType A_size = this->num_rows * this->num_columns;
         #pragma omp parallel
         {
             // Switch to a device with the same device id as the cpu thread id
             unsigned int thread_id = omp_get_thread_num();
             CudaInterface<DataType>::set_device(thread_id);
             // Allocate device memory and copy data from host
             CudaInterface<DataType>::alloc(this->device_A[thread_id], A_size);
             CudaInterface<DataType>::copy_to_device(this->A, A_size,
                                                     this->device_A[thread_id]);
         }
         // Flag to prevent reinitialization
         this->copied_host_to_device = true;
     }
 }
References CudaInterface< ArrayType >::alloc(), CudaInterface< ArrayType >::copy_to_device(), and CudaInterface< ArrayType >::set_device().
Referenced by cuDenseMatrix< DataType >::cuDenseMatrix().
dot()
template<typename DataType > void cuDenseMatrix< DataType >::dot (const DataType * device_vector, DataType * device_product) virtual
Reimplemented from cDenseMatrix< DataType >.
Definition at line 131 of file cu_dense_matrix.cu.
 {
     assert(this->copied_host_to_device);
     // Get device id
     int device_id = CudaInterface<DataType>::get_device();
     cuMatrixOperations<DataType>::dense_matvec(
             this->cublas_handle[device_id],
             this->device_A[device_id],
             device_vector,
             this->num_rows,
             this->num_columns,
             this->A_is_row_major,
             device_product);
 }
References cuMatrixOperations< DataType >::dense_matvec(), and CudaInterface< ArrayType >::get_device().
dot_plus()
template<typename DataType > void cuDenseMatrix< DataType >::dot_plus (const DataType * device_vector, const DataType alpha, DataType * device_product) virtual
Reimplemented from cDenseMatrix< DataType >.
Definition at line 156 of file cu_dense_matrix.cu.
 {
     assert(this->copied_host_to_device);
     // Get device id
     int device_id = CudaInterface<DataType>::get_device();
     cuMatrixOperations<DataType>::dense_matvec_plus(
             this->cublas_handle[device_id],
             this->device_A[device_id],
             device_vector,
             alpha,
             this->num_rows,
             this->num_columns,
             this->A_is_row_major,
             device_product);
 }
References cuMatrixOperations< DataType >::dense_matvec_plus(), and CudaInterface< ArrayType >::get_device().
transpose_dot()
template<typename DataType > void cuDenseMatrix< DataType >::transpose_dot (const DataType * device_vector, DataType * device_product) virtual
Reimplemented from cDenseMatrix< DataType >.
Definition at line 183 of file cu_dense_matrix.cu.
 {
     assert(this->copied_host_to_device);
     // Get device id
     int device_id = CudaInterface<DataType>::get_device();
     cuMatrixOperations<DataType>::dense_transposed_matvec(
             this->cublas_handle[device_id],
             this->device_A[device_id],
             device_vector,
             this->num_rows,
             this->num_columns,
             this->A_is_row_major,
             device_product);
 }
References cuMatrixOperations< DataType >::dense_transposed_matvec(), and CudaInterface< ArrayType >::get_device().
transpose_dot_plus()
template<typename DataType > void cuDenseMatrix< DataType >::transpose_dot_plus (const DataType * device_vector, const DataType alpha, DataType * device_product) virtual
Reimplemented from cDenseMatrix< DataType >.
Definition at line 208 of file cu_dense_matrix.cu.
 {
     assert(this->copied_host_to_device);
     // Get device id
     int device_id = CudaInterface<DataType>::get_device();
     cuMatrixOperations<DataType>::dense_transposed_matvec_plus(
             this->cublas_handle[device_id],
             this->device_A[device_id],
             device_vector,
             alpha,
             this->num_rows,
             this->num_columns,
             this->A_is_row_major,
             device_product);
 }
References cuMatrixOperations< DataType >::dense_transposed_matvec_plus(), and CudaInterface< ArrayType >::get_device().
Member Data Documentation
device_A
template<typename DataType > DataType** cuDenseMatrix< DataType >::device_A protected
Definition at line 72 of file cu_dense_matrix.h.
The documentation for this class was generated from the following files:
/home/runner/work/imate/imate/imate/_cu_linear_operator/cu_dense_matrix.h
/home/runner/work/imate/imate/imate/_cu_linear_operator/cu_dense_matrix.cu