imate: /home/runner/work/imate/imate/imate/_cuda_dynamic_loading/cublas_symbols.cpp File Reference
cublas_symbols.cpp File Reference
#include "./cublas_symbols.h"
#include <cublas_api.h>
#include <cstdlib>
#include <sstream>
#include "./dynamic_loading.h"
Functions
cublasStatus_t cublasCreate_v2 (cublasHandle_t *handle)
Definition of CUDA's cublasCreate function using dynamically loaded cublas library.
cublasStatus_t cublasDestroy_v2 (cublasHandle_t handle)
Definition of CUDA's cublasDestroy function using dynamically loaded cublas library.
cublasStatus_t cublasSgemv_v2 (cublasHandle_t handle, cublasOperation_t trans, int m, int n, const float *alpha, const float *A, int lda, const float *x, int incx, const float *beta, float *y, int incy)
Definition of CUDA's cublasSgemv function using dynamically loaded cublas library.
cublasStatus_t cublasDgemv_v2 (cublasHandle_t handle, cublasOperation_t trans, int m, int n, const double *alpha, const double *A, int lda, const double *x, int incx, const double *beta, double *y, int incy)
Definition of CUDA's cublasDgemv function using dynamically loaded cublas library.
cublasStatus_t cublasScopy (cublasHandle_t handle, int n, const float *x, int incx, float *y, int incy)
Definition of CUDA's cublasScopy function using dynamically loaded cublas library.
cublasStatus_t cublasDcopy (cublasHandle_t handle, int n, const double *x, int incx, double *y, int incy)
Definition of CUDA's cublasDcopy function using dynamically loaded cublas library.
cublasStatus_t cublasSaxpy (cublasHandle_t handle, int n, const float *alpha, const float *x, int incx, float *y, int incy)
Definition of CUDA's cublasSaxpy function using dynamically loaded cublas library.
cublasStatus_t cublasDaxpy (cublasHandle_t handle, int n, const double *alpha, const double *x, int incx, double *y, int incy)
Definition of CUDA's cublasDaxpy function using dynamically loaded cublas library.
cublasStatus_t cublasSdot (cublasHandle_t handle, int n, const float *x, int incx, const float *y, int incy, float *result)
Definition of CUDA's cublasSdot function using dynamically loaded cublas library.
cublasStatus_t cublasDdot (cublasHandle_t handle, int n, const double *x, int incx, const double *y, int incy, double *result)
Definition of CUDA's cublasDdot function using dynamically loaded cublas library.
cublasStatus_t cublasSnrm2 (cublasHandle_t handle, int n, const float *x, int incx, float *result)
Definition of CUDA's cublasSnrm2 function using dynamically loaded cublas library.
cublasStatus_t cublasDnrm2 (cublasHandle_t handle, int n, const double *x, int incx, double *result)
Definition of CUDA's cublasDnrm2 function using dynamically loaded cublas library.
cublasStatus_t cublasSscal (cublasHandle_t handle, int n, const float *alpha, float *x, int incx)
Definition of CUDA's cublasSscal function using dynamically loaded cublas library.
cublasStatus_t cublasDscal (cublasHandle_t handle, int n, const double *alpha, double *x, int incx)
Definition of CUDA's cublasDscal function using dynamically loaded cublas library.
Function Documentation
cublasCreate_v2()
cublasStatus_t cublasCreate_v2 (cublasHandle_t * handle)
Definition of CUDA's cublasCreate function using dynamically loaded cublas library.
Definition at line 97 of file cublas_symbols.cpp.
 {
     if (cublasSymbols::cublasCreate == NULL)
     {
         std::string lib_name = cublasSymbols::get_lib_name();
         const char* symbol_name = "cublasCreate_v2";
         cublasSymbols::cublasCreate = \
                 dynamic_loading::load_symbol<cublasCreate_type>(
                         lib_name.c_str(),
                         symbol_name);
     }
     return cublasSymbols::cublasCreate(handle);
 }
References cublasSymbols::cublasCreate, and cublasSymbols::get_lib_name().
cublasDaxpy()
cublasStatus_t cublasDaxpy (cublasHandle_t handle, int n, const double * alpha, const double * x, int incx, double * y, int incy)
Definition of CUDA's cublasDaxpy function using dynamically loaded cublas library.
Definition at line 308 of file cublas_symbols.cpp.
 {
     if (cublasSymbols::cublasDaxpy == NULL)
     {
         std::string lib_name = cublasSymbols::get_lib_name();
         const char* symbol_name = "cublasDaxpy_v2";
         cublasSymbols::cublasDaxpy = \
             dynamic_loading::load_symbol<cublasDaxpy_type>(
                     lib_name.c_str(),
                     symbol_name);
     }
     return cublasSymbols::cublasDaxpy(handle, n, alpha, x, incx, y, incy);
 }
References cublasSymbols::cublasDaxpy, and cublasSymbols::get_lib_name().
Referenced by cublas_interface::cublasXaxpy< double >().
cublasDcopy()
cublasStatus_t cublasDcopy (cublasHandle_t handle, int n, const double * x, int incx, double * y, int incy)
Definition of CUDA's cublasDcopy function using dynamically loaded cublas library.
Definition at line 248 of file cublas_symbols.cpp.
 {
     if (cublasSymbols::cublasDcopy == NULL)
     {
         std::string lib_name = cublasSymbols::get_lib_name();
         const char* symbol_name = "cublasDcopy_v2";
         cublasSymbols::cublasDcopy = \
             dynamic_loading::load_symbol<cublasDcopy_type>(
                     lib_name.c_str(),
                     symbol_name);
     }
     return cublasSymbols::cublasDcopy(handle, n, x, incx, y, incy);
 }
References cublasSymbols::cublasDcopy, and cublasSymbols::get_lib_name().
Referenced by cublas_interface::cublasXcopy< double >().
cublasDdot()
cublasStatus_t cublasDdot (cublasHandle_t handle, int n, const double * x, int incx, const double * y, int incy, double * result)
Definition of CUDA's cublasDdot function using dynamically loaded cublas library.
Definition at line 370 of file cublas_symbols.cpp.
 {
     if (cublasSymbols::cublasDdot == NULL)
     {
         std::string lib_name = cublasSymbols::get_lib_name();
         const char* symbol_name = "cublasDdot_v2";
         cublasSymbols::cublasDdot = \
             dynamic_loading::load_symbol<cublasDdot_type>(
                     lib_name.c_str(),
                     symbol_name);
     }
     return cublasSymbols::cublasDdot(handle, n, x, incx, y, incy, result);
 }
References cublasSymbols::cublasDdot, and cublasSymbols::get_lib_name().
Referenced by cublas_interface::cublasXdot< double >().
cublasDestroy_v2()
cublasStatus_t cublasDestroy_v2 (cublasHandle_t handle)
Definition of CUDA's cublasDestroy function using dynamically loaded cublas library.
Definition at line 122 of file cublas_symbols.cpp.
 {
     if (cublasSymbols::cublasDestroy == NULL)
     {
         std::string lib_name = cublasSymbols::get_lib_name();
         const char* symbol_name = "cublasDestroy_v2";
         cublasSymbols::cublasDestroy = \
                 dynamic_loading::load_symbol<cublasDestroy_type>(
                         lib_name.c_str(),
                         symbol_name);
     }
     return cublasSymbols::cublasDestroy(handle);
 }
References cublasSymbols::cublasDestroy, and cublasSymbols::get_lib_name().
cublasDgemv_v2()
cublasStatus_t cublasDgemv_v2 (cublasHandle_t handle, cublasOperation_t trans, int m, int n, const double * alpha, const double * A, int lda, const double * x, int incx, const double * beta, double * y, int incy)
Definition of CUDA's cublasDgemv function using dynamically loaded cublas library.
Definition at line 182 of file cublas_symbols.cpp.
 {
     if (cublasSymbols::cublasDgemv == NULL)
     {
         std::string lib_name = cublasSymbols::get_lib_name();
         const char* symbol_name = "cublasDgemv_v2";
         cublasSymbols::cublasDgemv = \
             dynamic_loading::load_symbol<cublasDgemv_type>(
                     lib_name.c_str(),
                     symbol_name);
     }
     return cublasSymbols::cublasDgemv(handle, trans, m, n, alpha, A, lda, x,
                                       incx, beta, y, incy);
 }
References cublasSymbols::cublasDgemv, and cublasSymbols::get_lib_name().
cublasDnrm2()
cublasStatus_t cublasDnrm2 (cublasHandle_t handle, int n, const double * x, int incx, double * result)
Definition of CUDA's cublasDnrm2 function using dynamically loaded cublas library.
Definition at line 430 of file cublas_symbols.cpp.
 {
     if (cublasSymbols::cublasDnrm2 == NULL)
     {
         std::string lib_name = cublasSymbols::get_lib_name();
         const char* symbol_name = "cublasDnrm2_v2";
         cublasSymbols::cublasDnrm2 = \
             dynamic_loading::load_symbol<cublasDnrm2_type>(
                     lib_name.c_str(),
                     symbol_name);
     }
     return cublasSymbols::cublasDnrm2(handle, n, x, incx, result);
 }
References cublasSymbols::cublasDnrm2, and cublasSymbols::get_lib_name().
Referenced by cublas_interface::cublasXnrm2< double >().
cublasDscal()
cublasStatus_t cublasDscal (cublasHandle_t handle, int n, const double * alpha, double * x, int incx)
Definition of CUDA's cublasDscal function using dynamically loaded cublas library.
Definition at line 488 of file cublas_symbols.cpp.
 {
     if (cublasSymbols::cublasDscal == NULL)
     {
         std::string lib_name = cublasSymbols::get_lib_name();
         const char* symbol_name = "cublasDscal_v2";
         cublasSymbols::cublasDscal = \
             dynamic_loading::load_symbol<cublasDscal_type>(
                     lib_name.c_str(),
                     symbol_name);
     }
     return cublasSymbols::cublasDscal(handle, n, alpha, x, incx);
 }
References cublasSymbols::cublasDscal, and cublasSymbols::get_lib_name().
Referenced by cublas_interface::cublasXscal< double >().
cublasSaxpy()
cublasStatus_t cublasSaxpy (cublasHandle_t handle, int n, const float * alpha, const float * x, int incx, float * y, int incy)
Definition of CUDA's cublasSaxpy function using dynamically loaded cublas library.
Definition at line 277 of file cublas_symbols.cpp.
 {
     if (cublasSymbols::cublasSaxpy == NULL)
     {
         std::string lib_name = cublasSymbols::get_lib_name();
         const char* symbol_name = "cublasSaxpy_v2";
         cublasSymbols::cublasSaxpy = \
             dynamic_loading::load_symbol<cublasSaxpy_type>(
                     lib_name.c_str(),
                     symbol_name);
     }
     return cublasSymbols::cublasSaxpy(handle, n, alpha, x, incx, y, incy);
 }
References cublasSymbols::cublasSaxpy, and cublasSymbols::get_lib_name().
Referenced by cublas_interface::cublasXaxpy< float >().
cublasScopy()
cublasStatus_t cublasScopy (cublasHandle_t handle, int n, const float * x, int incx, float * y, int incy)
Definition of CUDA's cublasScopy function using dynamically loaded cublas library.
Definition at line 219 of file cublas_symbols.cpp.
 {
     if (cublasSymbols::cublasScopy == NULL)
     {
         std::string lib_name = cublasSymbols::get_lib_name();
         const char* symbol_name = "cublasScopy_v2";
         cublasSymbols::cublasScopy = \
             dynamic_loading::load_symbol<cublasScopy_type>(
                     lib_name.c_str(),
                     symbol_name);
     }
     return cublasSymbols::cublasScopy(handle, n, x, incx, y, incy);
 }
References cublasSymbols::cublasScopy, and cublasSymbols::get_lib_name().
Referenced by cublas_interface::cublasXcopy< float >().
cublasSdot()
cublasStatus_t cublasSdot (cublasHandle_t handle, int n, const float * x, int incx, const float * y, int incy, float * result)
Definition of CUDA's cublasSdot function using dynamically loaded cublas library.
Definition at line 339 of file cublas_symbols.cpp.
 {
     if (cublasSymbols::cublasSdot == NULL)
     {
         std::string lib_name = cublasSymbols::get_lib_name();
         const char* symbol_name = "cublasSdot_v2";
         cublasSymbols::cublasSdot = \
             dynamic_loading::load_symbol<cublasSdot_type>(
                     lib_name.c_str(),
                     symbol_name);
     }
     return cublasSymbols::cublasSdot(handle, n, x, incx, y, incy, result);
 }
References cublasSymbols::cublasSdot, and cublasSymbols::get_lib_name().
Referenced by cublas_interface::cublasXdot< float >().
cublasSgemv_v2()
cublasStatus_t cublasSgemv_v2 (cublasHandle_t handle, cublasOperation_t trans, int m, int n, const float * alpha, const float * A, int lda, const float * x, int incx, const float * beta, float * y, int incy)
Definition of CUDA's cublasSgemv function using dynamically loaded cublas library.
Definition at line 145 of file cublas_symbols.cpp.
 {
     if (cublasSymbols::cublasSgemv == NULL)
     {
         std::string lib_name = cublasSymbols::get_lib_name();
         const char* symbol_name = "cublasSgemv_v2";
         cublasSymbols::cublasSgemv = \
             dynamic_loading::load_symbol<cublasSgemv_type>(
                     lib_name.c_str(),
                     symbol_name);
     }
     return cublasSymbols::cublasSgemv(handle, trans, m, n, alpha, A, lda, x,
                                       incx, beta, y, incy);
 }
References cublasSymbols::cublasSgemv, and cublasSymbols::get_lib_name().
cublasSnrm2()
cublasStatus_t cublasSnrm2 (cublasHandle_t handle, int n, const float * x, int incx, float * result)
Definition of CUDA's cublasSnrm2 function using dynamically loaded cublas library.
Definition at line 401 of file cublas_symbols.cpp.
 {
     if (cublasSymbols::cublasSnrm2 == NULL)
     {
         std::string lib_name = cublasSymbols::get_lib_name();
         const char* symbol_name = "cublasSnrm2_v2";
         cublasSymbols::cublasSnrm2 = \
             dynamic_loading::load_symbol<cublasSnrm2_type>(
                     lib_name.c_str(),
                     symbol_name);
     }
     return cublasSymbols::cublasSnrm2(handle, n, x, incx, result);
 }
References cublasSymbols::cublasSnrm2, and cublasSymbols::get_lib_name().
Referenced by cublas_interface::cublasXnrm2< float >().
cublasSscal()
cublasStatus_t cublasSscal (cublasHandle_t handle, int n, const float * alpha, float * x, int incx)
Definition of CUDA's cublasSscal function using dynamically loaded cublas library.
Definition at line 459 of file cublas_symbols.cpp.
 {
     if (cublasSymbols::cublasSscal == NULL)
     {
         std::string lib_name = cublasSymbols::get_lib_name();
         const char* symbol_name = "cublasSscal_v2";
         cublasSymbols::cublasSscal = \
             dynamic_loading::load_symbol<cublasSscal_type>(
                     lib_name.c_str(),
                     symbol_name);
     }
     return cublasSymbols::cublasSscal(handle, n, alpha, x, incx);
 }
References cublasSymbols::cublasSscal, and cublasSymbols::get_lib_name().
Referenced by cublas_interface::cublasXscal< float >().