imate: /home/runner/work/imate/imate/imate/_cuda_dynamic_loading/cudart_symbols.cpp File Reference
cudart_symbols.cpp File Reference
#include "./cudart_symbols.h"
#include <cuda_runtime_api.h>
#include <cstdlib>
#include <sstream>
#include "./dynamic_loading.h"
Functions
cudaError_t cudaEventCreate (cudaEvent_t *event)
Definition of CUDA's cudaEventCreate function using dynamically loaded cudart library.
cudaError_t cudaEventDestroy (cudaEvent_t event)
Definition of CUDA's cudaEventDestroy function using dynamically loaded cudart library.
cudaError_t cudaEventElapsedTime (float *ms, cudaEvent_t start, cudaEvent_t end)
Definition of CUDA's cudaEventElapsedTime function using dynamically loaded cudart library.
cudaError_t cudaEventRecord (cudaEvent_t event, cudaStream_t stream)
Definition of CUDA's cudaEventRecord function using dynamically loaded cudart library.
cudaError_t cudaEventSynchronize (cudaEvent_t event)
Definition of CUDA's cudaEventSynchronize function using dynamically loaded cudart library.
cudaError_t cudaGetDevice (int *device)
Definition of CUDA's cudaGetDevice function using dynamically loaded cudart library.
cudaError_t cudaGetDeviceCount (int *count)
Definition of CUDA's cudaGetDeviceCount function using dynamically loaded cudart library.
cudaError_t cudaGetDeviceProperties (cudaDeviceProp *prop, int device)
Definition of CUDA's cudaGetDeviceProperties function using dynamically loaded cudart library.
cudaError_t cudaFree (void *devPtr)
Definition of CUDA's cudaFree function using dynamically loaded cudart library.
cudaError_t cudaMalloc (void **devPtr, size_t size)
Definition of CUDA's cudaMalloc function using dynamically loaded cudart library.
cudaError_t cudaMemcpy (void *dst, const void *src, size_t count, cudaMemcpyKind kind)
Definition of CUDA's cudaMemcpy function using dynamically loaded cudart library.
cudaError_t cudaSetDevice (int device)
Definition of CUDA's cudaSetDevice function using dynamically loaded cudart library.
void ** __cudaRegisterFatBinary (void *fatCubin)
Definition of CUDA's __cudaRegisterFatBinary function using dynamically loaded cudart library.
void __cudaRegisterFatBinaryEnd (void **fatCubinHandle)
Definition of CUDA's __cudaRegisterFatBinaryEnd function using dynamically loaded cudart library.
void __cudaUnregisterFatBinary (void **fatCubinHandle)
Definition of CUDA's __cudaUnregisterFatBinary function using dynamically loaded cudart library.
Function Documentation
__cudaRegisterFatBinary()
void** __cudaRegisterFatBinary (void * fatCubin)
Definition of CUDA's __cudaRegisterFatBinary function using dynamically loaded cudart library.
Definition at line 402 of file cudart_symbols.cpp.
 {
     if (cudartSymbols::__cudaRegisterFatBinary == NULL)
     {
         std::string lib_name = cudartSymbols::get_lib_name();
         const char* symbol_name = "__cudaRegisterFatBinary";
         cudartSymbols::__cudaRegisterFatBinary = \
             dynamic_loading::load_symbol<__cudaRegisterFatBinary_type>(
                 lib_name.c_str(),
                 symbol_name);
     }
     return cudartSymbols::__cudaRegisterFatBinary(fatCubin);
 }
References cudartSymbols::__cudaRegisterFatBinary, and cudartSymbols::get_lib_name().
__cudaRegisterFatBinaryEnd()
void __cudaRegisterFatBinaryEnd (void ** fatCubinHandle)
Definition of CUDA's __cudaRegisterFatBinaryEnd function using dynamically loaded cudart library.
Definition at line 426 of file cudart_symbols.cpp.
 {
     if (cudartSymbols::__cudaRegisterFatBinaryEnd == NULL)
     {
         std::string lib_name = cudartSymbols::get_lib_name();
         const char* symbol_name = "__cudaRegisterFatBinaryEnd";
         cudartSymbols::__cudaRegisterFatBinaryEnd = \
             dynamic_loading::load_symbol<__cudaRegisterFatBinaryEnd_type>(
                 lib_name.c_str(),
                 symbol_name);
     }
     return cudartSymbols::__cudaRegisterFatBinaryEnd(fatCubinHandle);
 }
References cudartSymbols::__cudaRegisterFatBinaryEnd, and cudartSymbols::get_lib_name().
__cudaUnregisterFatBinary()
void __cudaUnregisterFatBinary (void ** fatCubinHandle)
Definition of CUDA's __cudaUnregisterFatBinary function using dynamically loaded cudart library.
Definition at line 450 of file cudart_symbols.cpp.
 {
     if (cudartSymbols::__cudaUnregisterFatBinary == NULL)
     {
         std::string lib_name = cudartSymbols::get_lib_name();
         const char* symbol_name = "__cudaUnregisterFatBinary";
         cudartSymbols::__cudaUnregisterFatBinary = \
             dynamic_loading::load_symbol<__cudaUnregisterFatBinary_type>(
                 lib_name.c_str(),
                 symbol_name);
     }
     return cudartSymbols::__cudaUnregisterFatBinary(fatCubinHandle);
 }
References cudartSymbols::__cudaUnregisterFatBinary, and cudartSymbols::get_lib_name().
cudaEventCreate()
cudaError_t cudaEventCreate (cudaEvent_t * event)
Definition of CUDA's cudaEventCreate function using dynamically loaded cudart library.
Definition at line 106 of file cudart_symbols.cpp.
 {
     if (cudartSymbols::cudaEventCreate == NULL)
     {
         std::string lib_name = cudartSymbols::get_lib_name();
         const char* symbol_name = "cudaEventCreate";
         cudartSymbols::cudaEventCreate = \
             dynamic_loading::load_symbol<cudaEventCreate_type>(
                 lib_name.c_str(),
                 symbol_name);
     }
     return cudartSymbols::cudaEventCreate(event);
 }
References cudartSymbols::cudaEventCreate, and cudartSymbols::get_lib_name().
Referenced by CudaTimer::CudaTimer().
cudaEventDestroy()
cudaError_t cudaEventDestroy (cudaEvent_t event)
Definition of CUDA's cudaEventDestroy function using dynamically loaded cudart library.
Definition at line 130 of file cudart_symbols.cpp.
 {
     if (cudartSymbols::cudaEventDestroy == NULL)
     {
         std::string lib_name = cudartSymbols::get_lib_name();
         const char* symbol_name = "cudaEventDestroy";
         cudartSymbols::cudaEventDestroy = \
             dynamic_loading::load_symbol<cudaEventDestroy_type>(
                 lib_name.c_str(),
                 symbol_name);
     }
     return cudartSymbols::cudaEventDestroy(event);
 }
References cudartSymbols::cudaEventDestroy, and cudartSymbols::get_lib_name().
Referenced by CudaTimer::~CudaTimer().
cudaEventElapsedTime()
cudaError_t cudaEventElapsedTime (float * ms, cudaEvent_t start, cudaEvent_t end)
Definition of CUDA's cudaEventElapsedTime function using dynamically loaded cudart library.
Definition at line 154 of file cudart_symbols.cpp.
 {
     if (cudartSymbols::cudaEventElapsedTime == NULL)
     {
         std::string lib_name = cudartSymbols::get_lib_name();
         const char* symbol_name = "cudaEventElapsedTime";
         cudartSymbols::cudaEventElapsedTime = \
             dynamic_loading::load_symbol<cudaEventElapsedTime_type>(
                 lib_name.c_str(),
                 symbol_name);
     }
     return cudartSymbols::cudaEventElapsedTime(ms, start, end);
 }
References cudartSymbols::cudaEventElapsedTime, and cudartSymbols::get_lib_name().
Referenced by CudaTimer::elapsed().
cudaEventRecord()
cudaError_t cudaEventRecord (cudaEvent_t event, cudaStream_t stream)
Definition of CUDA's cudaEventRecord function using dynamically loaded cudart library.
Definition at line 181 of file cudart_symbols.cpp.
 {
     if (cudartSymbols::cudaEventRecord == NULL)
     {
         std::string lib_name = cudartSymbols::get_lib_name();
         const char* symbol_name = "cudaEventRecord";
         cudartSymbols::cudaEventRecord = \
             dynamic_loading::load_symbol<cudaEventRecord_type>(
                 lib_name.c_str(),
                 symbol_name);
     }
     return cudartSymbols::cudaEventRecord(event, stream);
 }
References cudartSymbols::cudaEventRecord, and cudartSymbols::get_lib_name().
Referenced by CudaTimer::start(), and CudaTimer::stop().
cudaEventSynchronize()
cudaError_t cudaEventSynchronize (cudaEvent_t event)
Definition of CUDA's cudaEventSynchronize function using dynamically loaded cudart library.
Definition at line 205 of file cudart_symbols.cpp.
 {
     if (cudartSymbols::cudaEventSynchronize == NULL)
     {
         std::string lib_name = cudartSymbols::get_lib_name();
         const char* symbol_name = "cudaEventSynchronize";
         cudartSymbols::cudaEventSynchronize = \
             dynamic_loading::load_symbol<cudaEventSynchronize_type>(
                 lib_name.c_str(),
                 symbol_name);
     }
     return cudartSymbols::cudaEventSynchronize(event);
 }
References cudartSymbols::cudaEventSynchronize, and cudartSymbols::get_lib_name().
Referenced by CudaTimer::elapsed().
cudaFree()
cudaError_t cudaFree (void * devPtr)
Definition of CUDA's cudaFree function using dynamically loaded cudart library.
Definition at line 303 of file cudart_symbols.cpp.
 {
     if (cudartSymbols::cudaFree == NULL)
     {
         std::string lib_name = cudartSymbols::get_lib_name();
         const char* symbol_name = "cudaFree";
         cudartSymbols::cudaFree = dynamic_loading::load_symbol<cudaFree_type>(
                 lib_name.c_str(),
                 symbol_name);
     }
     return cudartSymbols::cudaFree(devPtr);
 }
References cudartSymbols::cudaFree, and cudartSymbols::get_lib_name().
Referenced by CudaInterface< ArrayType >::del().
cudaGetDevice()
cudaError_t cudaGetDevice (int * device)
Definition of CUDA's cudaGetDevice function using dynamically loaded cudart library.
Definition at line 229 of file cudart_symbols.cpp.
 {
     if (cudartSymbols::cudaGetDevice == NULL)
     {
         std::string lib_name = cudartSymbols::get_lib_name();
         const char* symbol_name = "cudaGetDevice";
         cudartSymbols::cudaGetDevice = \
             dynamic_loading::load_symbol<cudaGetDevice_type>(
                 lib_name.c_str(),
                 symbol_name);
     }
     return cudartSymbols::cudaGetDevice(device);
 }
References cudartSymbols::cudaGetDevice, and cudartSymbols::get_lib_name().
Referenced by CudaInterface< ArrayType >::get_device().
cudaGetDeviceCount()
cudaError_t cudaGetDeviceCount (int * count)
Definition of CUDA's cudaGetDeviceCount function using dynamically loaded cudart library.
Definition at line 253 of file cudart_symbols.cpp.
 {
     if (cudartSymbols::cudaGetDeviceCount == NULL)
     {
         std::string lib_name = cudartSymbols::get_lib_name();
         const char* symbol_name = "cudaGetDeviceCount";
         cudartSymbols::cudaGetDeviceCount = \
             dynamic_loading::load_symbol<cudaGetDeviceCount_type>(
                 lib_name.c_str(),
                 symbol_name);
     }
     return cudartSymbols::cudaGetDeviceCount(count);
 }
References cudartSymbols::cudaGetDeviceCount, and cudartSymbols::get_lib_name().
Referenced by query_device(), and cuLinearOperator< DataType >::query_gpu_devices().
cudaGetDeviceProperties()
cudaError_t cudaGetDeviceProperties (cudaDeviceProp * prop, int device)
Definition of CUDA's cudaGetDeviceProperties function using dynamically loaded cudart library.
Definition at line 277 of file cudart_symbols.cpp.
 {
     if (cudartSymbols::cudaGetDeviceProperties == NULL)
     {
         std::string lib_name = cudartSymbols::get_lib_name();
         const char* symbol_name = "cudaGetDeviceProperties";
         cudartSymbols::cudaGetDeviceProperties = \
             dynamic_loading::load_symbol<cudaGetDeviceProperties_type>(
                 lib_name.c_str(),
                 symbol_name);
     }
     return cudartSymbols::cudaGetDeviceProperties(prop, device);
 }
References cudartSymbols::cudaGetDeviceProperties, and cudartSymbols::get_lib_name().
Referenced by query_device().
cudaMalloc()
cudaError_t cudaMalloc (void ** devPtr, size_t size)
Definition of CUDA's cudaMalloc function using dynamically loaded cudart library.
Definition at line 326 of file cudart_symbols.cpp.
 {
     if (cudartSymbols::cudaMalloc == NULL)
     {
         std::string lib_name = cudartSymbols::get_lib_name();
         const char* symbol_name = "cudaMalloc";
         cudartSymbols::cudaMalloc = \
             dynamic_loading::load_symbol<cudaMalloc_type>(
                 lib_name.c_str(),
                 symbol_name);
     }
     return cudartSymbols::cudaMalloc(devPtr, size);
 }
References cudartSymbols::cudaMalloc, and cudartSymbols::get_lib_name().
Referenced by CudaInterface< ArrayType >::alloc(), and CudaInterface< ArrayType >::alloc_bytes().
cudaMemcpy()
cudaError_t cudaMemcpy (void * dst, const void * src, size_t count, cudaMemcpyKind kind)
Definition of CUDA's cudaMemcpy function using dynamically loaded cudart library.
Definition at line 350 of file cudart_symbols.cpp.
 {
     if (cudartSymbols::cudaMemcpy == NULL)
     {
         std::string lib_name = cudartSymbols::get_lib_name();
         const char* symbol_name = "cudaMemcpy";
         cudartSymbols::cudaMemcpy = \
             dynamic_loading::load_symbol<cudaMemcpy_type>(
                 lib_name.c_str(),
                 symbol_name);
     }
     return cudartSymbols::cudaMemcpy(dst, src, count, kind);
 }
References cudartSymbols::cudaMemcpy, and cudartSymbols::get_lib_name().
Referenced by CudaInterface< ArrayType >::copy_to_device().
cudaSetDevice()
cudaError_t cudaSetDevice (int device)
Definition of CUDA's cudaSetDevice function using dynamically loaded cudart library.
Definition at line 378 of file cudart_symbols.cpp.
 {
     if (cudartSymbols::cudaSetDevice == NULL)
     {
         std::string lib_name = cudartSymbols::get_lib_name();
         const char* symbol_name = "cudaSetDevice";
         cudartSymbols::cudaSetDevice = \
             dynamic_loading::load_symbol<cudaSetDevice_type>(
                 lib_name.c_str(),
                 symbol_name);
     }
     return cudartSymbols::cudaSetDevice(device);
 }
References cudartSymbols::cudaSetDevice, and cudartSymbols::get_lib_name().
Referenced by CudaInterface< ArrayType >::set_device().