imate: /home/runner/work/imate/imate/imate/_cuda_dynamic_loading/cusparse_symbols.cpp File Reference
cusparse_symbols.cpp File Reference
#include "./cusparse_symbols.h"
#include <cusparse.h>
#include <cstdlib>
#include <sstream>
#include "./dynamic_loading.h"
Functions
cusparseStatus_t cusparseCreate (cusparseHandle_t *handle)
Definition of CUDA's cusparseCreate function using dynamically loaded cublas library.
cusparseStatus_t cusparseDestroy (cusparseHandle_t handle)
Definition of CUDA's cusparseDestroy function using dynamically loaded cublas library.
cusparseStatus_t cusparseCreateCsr (cusparseSpMatDescr_t *spMatDescr, int64_t rows, int64_t cols, int64_t nnz, void *csrRowOffsets, void *csrColInd, void *csrValues, cusparseIndexType_t csrRowOffsetsType, cusparseIndexType_t csrColIndType, cusparseIndexBase_t idxBase, cudaDataType valueType)
Definition of CUDA's cusparseCreateCsr function using dynamically loaded cublas library.
cusparseStatus_t cusparseCreateDnVec (cusparseDnVecDescr_t *dnVecDescr, int64_t size, void *values, cudaDataType valueType)
Definition of CUDA's cusparseCreateDnVec function using dynamically loaded cublas library.
cusparseStatus_t cusparseDestroySpMat (cusparseConstSpMatDescr_t spMatDescr)
Definition of CUDA's cusparseDestroySpMat function using dynamically loaded cublas library.
cusparseStatus_t cusparseDestroyDnVec (cusparseConstDnVecDescr_t dnVecDescr)
Definition of CUDA's cusparseDestroyDnVec function using dynamically loaded cublas library.
cusparseStatus_t cusparseSpMV_bufferSize (cusparseHandle_t handle, cusparseOperation_t opA, const void *alpha, cusparseConstSpMatDescr_t matA, cusparseConstDnVecDescr_t vecX, const void *beta, cusparseDnVecDescr_t vecY, cudaDataType computeType, cusparseSpMVAlg_t alg, size_t *bufferSize)
Definition of CUDA's cusparseSpMV_bufferSize function using dynamically loaded cublas library.
cusparseStatus_t cusparseSpMV (cusparseHandle_t handle, cusparseOperation_t opA, const void *alpha, cusparseConstSpMatDescr_t matA, cusparseConstDnVecDescr_t vecX, const void *beta, cusparseDnVecDescr_t vecY, cudaDataType computeType, cusparseSpMVAlg_t alg, void *externalBuffer)
Definition of CUDA's cusparseSmMV function using dynamically loaded cublas library.
Function Documentation
cusparseCreate()
cusparseStatus_t cusparseCreate (cusparseHandle_t * handle)
Definition of CUDA's cusparseCreate function using dynamically loaded cublas library.
Definition at line 92 of file cusparse_symbols.cpp.
 {
     if (cusparseSymbols::cusparseCreate == NULL)
     {
         std::string lib_name = cusparseSymbols::get_lib_name();
         const char* symbol_name = "cusparseCreate";
         cusparseSymbols::cusparseCreate = \
             dynamic_loading::load_symbol<cusparseCreate_type>(
                     lib_name.c_str(),
                     symbol_name);
     }
     return cusparseSymbols::cusparseCreate(handle);
 }
References cusparseSymbols::cusparseCreate, and cusparseSymbols::get_lib_name().
Referenced by cuLinearOperator< DataType >::initialize_cusparse_handle().
cusparseCreateCsr()
cusparseStatus_t cusparseCreateCsr (cusparseSpMatDescr_t * spMatDescr, int64_t rows, int64_t cols, int64_t nnz, void * csrRowOffsets, void * csrColInd, void * csrValues, cusparseIndexType_t csrRowOffsetsType, cusparseIndexType_t csrColIndType, cusparseIndexBase_t idxBase, cudaDataType valueType)
Definition of CUDA's cusparseCreateCsr function using dynamically loaded cublas library.
Definition at line 140 of file cusparse_symbols.cpp.
 {
     if (cusparseSymbols::cusparseCreateCsr == NULL)
     {
         std::string lib_name = cusparseSymbols::get_lib_name();
         const char* symbol_name = "cusparseCreateCsr";
         cusparseSymbols::cusparseCreateCsr = \
             dynamic_loading::load_symbol<cusparseCreateCsr_type>(
                     lib_name.c_str(),
                     symbol_name);
     }
     return cusparseSymbols::cusparseCreateCsr(
             spMatDescr, rows, cols, nnz, csrRowOffsets, csrColInd, csrValues,
             csrRowOffsetsType, csrColIndType, idxBase, valueType);
 }
References cusparseSymbols::cusparseCreateCsr, and cusparseSymbols::get_lib_name().
Referenced by cusparse_interface::create_cusparse_matrix< double >(), and cusparse_interface::create_cusparse_matrix< float >().
cusparseCreateDnVec()
cusparseStatus_t cusparseCreateDnVec (cusparseDnVecDescr_t * dnVecDescr, int64_t size, void * values, cudaDataType valueType)
Definition of CUDA's cusparseCreateDnVec function using dynamically loaded cublas library.
Definition at line 177 of file cusparse_symbols.cpp.
 {
     if (cusparseSymbols::cusparseCreateDnVec == NULL)
     {
         std::string lib_name = cusparseSymbols::get_lib_name();
         const char* symbol_name = "cusparseCreateDnVec";
         cusparseSymbols::cusparseCreateDnVec = \
             dynamic_loading::load_symbol<cusparseCreateDnVec_type>(
                     lib_name.c_str(),
                     symbol_name);
     }
     return cusparseSymbols::cusparseCreateDnVec(
         dnVecDescr, size, values, valueType);
 }
References cusparseSymbols::cusparseCreateDnVec, and cusparseSymbols::get_lib_name().
Referenced by cusparse_interface::create_cusparse_vector< double >(), and cusparse_interface::create_cusparse_vector< float >().
cusparseDestroy()
cusparseStatus_t cusparseDestroy (cusparseHandle_t handle)
Definition of CUDA's cusparseDestroy function using dynamically loaded cublas library.
Definition at line 116 of file cusparse_symbols.cpp.
 {
     if (cusparseSymbols::cusparseDestroy == NULL)
     {
         std::string lib_name = cusparseSymbols::get_lib_name();
         const char* symbol_name = "cusparseDestroy";
         cusparseSymbols::cusparseDestroy  = \
             dynamic_loading::load_symbol<cusparseDestroy_type>(
                     lib_name.c_str(),
                     symbol_name);
     }
     return cusparseSymbols::cusparseDestroy(handle);
 }
References cusparseSymbols::cusparseDestroy, and cusparseSymbols::get_lib_name().
Referenced by cuLinearOperator< DataType >::~cuLinearOperator().
cusparseDestroyDnVec()
cusparseStatus_t cusparseDestroyDnVec (cusparseConstDnVecDescr_t dnVecDescr)
Definition of CUDA's cusparseDestroyDnVec function using dynamically loaded cublas library.
Definition at line 231 of file cusparse_symbols.cpp.
 {
     if (cusparseSymbols::cusparseDestroyDnVec == NULL)
     {
         std::string lib_name = cusparseSymbols::get_lib_name();
         const char* symbol_name = "cusparseDestroyDnVec";
         cusparseSymbols::cusparseDestroyDnVec = \
             dynamic_loading::load_symbol<cusparseDestroyDnVec_type>(
                     lib_name.c_str(),
                     symbol_name);
     }
     return cusparseSymbols::cusparseDestroyDnVec(dnVecDescr);
 }
References cusparseSymbols::cusparseDestroyDnVec, and cusparseSymbols::get_lib_name().
Referenced by cusparse_interface::destroy_cusparse_vector().
cusparseDestroySpMat()
cusparseStatus_t cusparseDestroySpMat (cusparseConstSpMatDescr_t spMatDescr)
Definition of CUDA's cusparseDestroySpMat function using dynamically loaded cublas library.
Definition at line 206 of file cusparse_symbols.cpp.
 {
     if (cusparseSymbols::cusparseDestroySpMat == NULL)
     {
         std::string lib_name = cusparseSymbols::get_lib_name();
         const char* symbol_name = "cusparseDestroySpMat";
         cusparseSymbols::cusparseDestroySpMat = \
             dynamic_loading::load_symbol<cusparseDestroySpMat_type>(
                     lib_name.c_str(),
                     symbol_name);
     }
     return cusparseSymbols::cusparseDestroySpMat(spMatDescr);
 }
References cusparseSymbols::cusparseDestroySpMat, and cusparseSymbols::get_lib_name().
Referenced by cusparse_interface::destroy_cusparse_matrix().
cusparseSpMV()
cusparseStatus_t cusparseSpMV (cusparseHandle_t handle, cusparseOperation_t opA, const void * alpha, cusparseConstSpMatDescr_t matA, cusparseConstDnVecDescr_t vecX, const void * beta, cusparseDnVecDescr_t vecY, cudaDataType computeType, cusparseSpMVAlg_t alg, void * externalBuffer)
Definition of CUDA's cusparseSmMV function using dynamically loaded cublas library.
Definition at line 292 of file cusparse_symbols.cpp.
 {
     if (cusparseSymbols::cusparseSpMV == NULL)
     {
         std::string lib_name = cusparseSymbols::get_lib_name();
         const char* symbol_name = "cusparseSpMV";
         cusparseSymbols::cusparseSpMV = \
             dynamic_loading::load_symbol<cusparseSpMV_type>(
                     lib_name.c_str(),
                     symbol_name);
     }
     return cusparseSymbols::cusparseSpMV(
             handle, opA, alpha, matA, vecX, beta, vecY, computeType, alg,
             externalBuffer);
 }
References cusparseSymbols::cusparseSpMV, and cusparseSymbols::get_lib_name().
Referenced by cusparse_interface::cusparse_matvec< double >(), and cusparse_interface::cusparse_matvec< float >().
cusparseSpMV_bufferSize()
cusparseStatus_t cusparseSpMV_bufferSize (cusparseHandle_t handle, cusparseOperation_t opA, const void * alpha, cusparseConstSpMatDescr_t matA, cusparseConstDnVecDescr_t vecX, const void * beta, cusparseDnVecDescr_t vecY, cudaDataType computeType, cusparseSpMVAlg_t alg, size_t * bufferSize)
Definition of CUDA's cusparseSpMV_bufferSize function using dynamically loaded cublas library.
Definition at line 256 of file cusparse_symbols.cpp.
 {
     if (cusparseSymbols::cusparseSpMV_bufferSize == NULL)
     {
         std::string lib_name = cusparseSymbols::get_lib_name();
         const char* symbol_name = "cusparseSpMV_bufferSize";
         cusparseSymbols::cusparseSpMV_bufferSize = \
             dynamic_loading::load_symbol<cusparseSpMV_bufferSize_type>(
                     lib_name.c_str(),
                     symbol_name);
     }
     return cusparseSymbols::cusparseSpMV_bufferSize(
             handle, opA, alpha, matA, vecX, beta, vecY, computeType, alg,
             bufferSize);
 }
References cusparseSymbols::cusparseSpMV_bufferSize, and cusparseSymbols::get_lib_name().
Referenced by cusparse_interface::cusparse_matrix_buffer_size< double >(), and cusparse_interface::cusparse_matrix_buffer_size< float >().