imate: /home/runner/work/imate/imate/imate/_c_trace_estimator/lapack_api.h File Reference
lapack_api.h File Reference
Functions
void lapack_sstev (char *jobz, int *n, float *d, float *e, float *z, int *ldz, float *work, int *info)
void lapack_dstev (char *jobz, int *n, double *d, double *e, double *z, int *ldz, double *work, int *info)
void lapack_sbdsdc (char *uplo, char *compq, int *n, float *d, float *e, float *u, int *ldu, float *vt, int *ldvt, float *q, int *iq, float *work, int *iwork, int *info)
void lapack_dbdsdc (char *uplo, char *compq, int *n, double *d, double *e, double *u, int *ldu, double *vt, int *ldvt, double *q, int *iq, double *work, int *iwork, int *info)
template<typename DataType >
void lapack_xstev (char *jobz, int *n, DataType *d, DataType *e, DataType *z, int *ldz, DataType *work, int *info)
template<typename DataType >
void lapack_xbdsdc (char *uplo, char *compq, int *n, DataType *d, DataType *e, DataType *u, int *ldu, DataType *vt, int *ldvt, DataType *q, int *iq, DataType *work, int *iwork, int *info)
Function Documentation
lapack_dbdsdc()
void lapack_dbdsdc (char * uplo, char * compq, int * n, double * d, double * e, double * u, int * ldu, double * vt, int * ldvt, double * q, int * iq, double * work, int * iwork, int * info)
Referenced by lapack_xbdsdc< double >(), and lapack_xbdsdc< long double >().
lapack_dstev()
void lapack_dstev (char * jobz, int * n, double * d, double * e, double * z, int * ldz, double * work, int * info)
Referenced by lapack_xstev< double >(), and lapack_xstev< long double >().
lapack_sbdsdc()
void lapack_sbdsdc (char * uplo, char * compq, int * n, float * d, float * e, float * u, int * ldu, float * vt, int * ldvt, float * q, int * iq, float * work, int * iwork, int * info)
Referenced by lapack_xbdsdc< float >().
lapack_sstev()
void lapack_sstev (char * jobz, int * n, float * d, float * e, float * z, int * ldz, float * work, int * info)
Referenced by lapack_xstev< float >().
lapack_xbdsdc()
template<typename DataType > void lapack_xbdsdc (char * uplo, char * compq, int * n, DataType * d, DataType * e, DataType * u, int * ldu, DataType * vt, int * ldvt, DataType * q, int * iq, DataType * work, int * iwork, int * info)
Referenced by Diagonalization< DataType >::svd_bidiagonal().
lapack_xstev()
template<typename DataType > void lapack_xstev (char * jobz, int * n, DataType * d, DataType * e, DataType * z, int * ldz, DataType * work, int * info)
Referenced by Diagonalization< DataType >::eigh_tridiagonal().