imate: /home/runner/work/imate/imate/imate/_c_trace_estimator/lapack_api.cpp File Reference
lapack_api.cpp File Reference
#include "./lapack_api.h"
#include <cstddef>
Functions
template<>
void lapack_xstev< float > (char *jobz, int *n, float *d, float *e, float *z, int *ldz, float *work, int *info)
Overlodng wrapper for both lapack_sstev (a float function) and lapack_dstev (a double function). xstev overloads both sstev and dstev with the same function signature.
template<>
void lapack_xstev< double > (char *jobz, int *n, double *d, double *e, double *z, int *ldz, double *work, int *info)
Overlodng wrapper for both lapack_sstev (a float function) and lapack_dstev (a double function). xstev overloads both sstev and dstev with the same function signature.
template<>
void lapack_xstev< long double > (char *jobz, int *n, long double *d, long double *e, long double *z, int *ldz, long double *work, int *info)
Overlodng wrapper for both lapack_sstev (a float function) and lapack_dstev (a double function). xstev overloads both sstev and dstev with the same function signature. This function casts long double type to double and uses dstev subroutine.
template<>
void lapack_xbdsdc< float > (char *uplo, char *compq, int *n, float *d, float *e, float *u, int *ldu, float *vt, int *ldvt, float *q, int *iq, float *work, int *iwork, int *info)
Overlodng wrapper for both lapack_sbdsdc (a float function) and lapack_dbdsdc (a double function). xbdsdc overloads both sbdsdc and dbdsdc with the same function signature.
template<>
void lapack_xbdsdc< double > (char *uplo, char *compq, int *n, double *d, double *e, double *u, int *ldu, double *vt, int *ldvt, double *q, int *iq, double *work, int *iwork, int *info)
Overlodng wrapper for both lapack_sbdsdc (a double function) and lapack_dbdsdc (a double function). xbdsdc overloads both sbdsdc and dbdsdc with the same function signature.
template<>
void lapack_xbdsdc< long double > (char *uplo, char *compq, int *n, long double *d, long double *e, long double *u, int *ldu, long double *vt, int *ldvt, long double *q, int *iq, long double *work, int *iwork, int *info)
Overlodng wrapper for both lapack_sbdsdc (a double function) and lapack_dbdsdc (a double function). xbdsdc overloads both sstev and dstev with the same function signature. This function casts long double type to double and uses dstev subroutine.
Function Documentation
lapack_xbdsdc< double >()
template<> void lapack_xbdsdc< double > (char * uplo, char * compq, int * n, double * d, double * e, double * u, int * ldu, double * vt, int * ldvt, double * q, int * iq, double * work, int * iwork, int * info)
Overlodng wrapper for both lapack_sbdsdc (a double function) and lapack_dbdsdc (a double function). xbdsdc overloads both sbdsdc and dbdsdc with the same function signature.
Definition at line 142 of file lapack_api.cpp.
 {
     lapack_dbdsdc(uplo, compq, n, d, e, u, ldu, vt, ldvt, q, iq, work, iwork,
                   info);
 }
References lapack_dbdsdc().
lapack_xbdsdc< float >()
template<> void lapack_xbdsdc< float > (char * uplo, char * compq, int * n, float * d, float * e, float * u, int * ldu, float * vt, int * ldvt, float * q, int * iq, float * work, int * iwork, int * info)
Overlodng wrapper for both lapack_sbdsdc (a float function) and lapack_dbdsdc (a double function). xbdsdc overloads both sbdsdc and dbdsdc with the same function signature.
Definition at line 124 of file lapack_api.cpp.
 {
     lapack_sbdsdc(uplo, compq, n, d, e, u, ldu, vt, ldvt, q, iq, work, iwork,
                   info);
 }
References lapack_sbdsdc().
lapack_xbdsdc< long double >()
template<> void lapack_xbdsdc< long double > (char * uplo, char * compq, int * n, long double * d, long double * e, long double * u, int * ldu, long double * vt, int * ldvt, long double * q, int * iq, long double * work, int * iwork, int * info)
Overlodng wrapper for both lapack_sbdsdc (a double function) and lapack_dbdsdc (a double function). xbdsdc overloads both sstev and dstev with the same function signature. This function casts long double type to double and uses dstev subroutine.
The variables with leading undescore are double counterparts of the long double variables.
Definition at line 166 of file lapack_api.cpp.
 {
     // Mark unused variables to avoid compiler warnings (-Wno-unused-parameter)
     (void) q;
     (void) work;
     // Deep copy long double diagonal array to double
     double *d_ = new double[(*n)];
     for (int i=0; i < (*n); ++i)
     {
         d_[i] = static_cast<double>(d[i]);
     }
     // Deep copy long double supdiagonal array to double
     double *e_ = new double[(*n)-1];
     for (int i=0; i < (*n)-1; ++i)
     {
         e_[i] = static_cast<double>(e[i]);
     }
     // Declare left and right eigenvectors arrays
     double *u_ = new double[(*ldu)*(*n)];
     double *vt_ = new double[(*ldvt)*(*n)];
     // Declare work variables
     double* q_ = NULL;
     double *work_ = new double[3*(*n)*(*n) + 4*(*n)];
     // Call lapack
     lapack_dbdsdc(uplo, compq, n, d_, e_, u_, ldu, vt_, ldvt, q_, iq, work_,
                   iwork, info);
     // Copy back eigenvectors from double to long double
     for (int i=0; i < (*n); ++i)
     {
         d[i] = static_cast<long double>(d_[i]);
     }
     // Copy left and right eigenvectors fom double to long double
     for (int i=0; i < (*ldu)*(*n); ++i)
     {
         u[i] = static_cast<long double>(u_[i]);
     }
     for (int i=0; i < (*ldvt)*(*n); ++i)
     {
         vt[i] = static_cast<long double>(vt_[i]);
     }
     // Deallocate memory
     delete[] d_;
     delete[] e_;
     delete[] u_;
     delete[] vt_;
     delete[] work_;
 }
References lapack_dbdsdc().
lapack_xstev< double >()
template<> void lapack_xstev< double > (char * jobz, int * n, double * d, double * e, double * z, int * ldz, double * work, int * info)
Overlodng wrapper for both lapack_sstev (a float function) and lapack_dstev (a double function). xstev overloads both sstev and dstev with the same function signature.
Definition at line 46 of file lapack_api.cpp.
 {
     // Calling double method
     lapack_dstev(jobz, n, d, e, z, ldz, work, info);
 }
References lapack_dstev().
lapack_xstev< float >()
template<> void lapack_xstev< float > (char * jobz, int * n, float * d, float * e, float * z, int * ldz, float * work, int * info)
Overlodng wrapper for both lapack_sstev (a float function) and lapack_dstev (a double function). xstev overloads both sstev and dstev with the same function signature.
Definition at line 29 of file lapack_api.cpp.
 {
     // Calling float method
     lapack_sstev(jobz, n, d, e, z, ldz, work, info);
 }
lapack_xstev< long double >()
template<> void lapack_xstev< long double > (char * jobz, int * n, long double * d, long double * e, long double * z, int * ldz, long double * work, int * info)
Overlodng wrapper for both lapack_sstev (a float function) and lapack_dstev (a double function). xstev overloads both sstev and dstev with the same function signature. This function casts long double type to double and uses dstev subroutine.
The variables with leading undescore are double counterparts of the long double variables.
Definition at line 67 of file lapack_api.cpp.
 {
     // Mark unused variables to avoid compiler warnings (-Wno-unused-parameter)
     (void) work;
     // Deep copy long double diagonal array to double
     double *d_ = new double[(*n)];
     for (int i=0; i < (*n); ++i)
     {
         d_[i] = static_cast<double>(d[i]);
     }
     // Deep copy long double supdiagonal array to double
     double *e_ = new double[(*n)-1];
     for (int i=0; i < (*n)-1; ++i)
     {
         e_[i] = static_cast<double>(e[i]);
     }
     // Declare eigenvectors and work arrays as double
     double *z_ = new double[(*ldz)*(*n)];
     double *work_ = new double[2*(*n)-2];
     // Calling double method
     lapack_dstev(jobz, n, d_, e_, z_, ldz, work_, info);
     // Copy eigenvalues from double to long double
     for (int i=0; i < (*n); ++i)
     {
         d[i] = static_cast<long double>(d_[i]);
     }
     // Copy eigenvectors from double to long double
     for (int i=0; i < (*ldz)*(*n); ++i)
     {
         z[i] = static_cast<long double>(z_[i]);
     }
     // Deallocate memory
     delete[] d_;
     delete[] e_;
     delete[] z_;
     delete[] work_;
 }
References lapack_dstev().