imate: cusparse_interface Namespace Reference
cusparse_interface Namespace Reference
A collection of templates to wrapper cusparse functions.
Functions
template<>
void create_cusparse_matrix< float > (cusparseSpMatDescr_t &cusparse_matrix, const LongIndexType num_rows, const LongIndexType num_columns, const LongIndexType nnz, float *device_A_data, LongIndexType *device_A_indices, LongIndexType *device_A_index_pointer)
A template wrapper for cusparseSpMatDescr_t for the float precision data.
template<>
void create_cusparse_matrix< double > (cusparseSpMatDescr_t &cusparse_matrix, const LongIndexType num_rows, const LongIndexType num_columns, const LongIndexType nnz, double *device_A_data, LongIndexType *device_A_indices, LongIndexType *device_A_index_pointer)
A template wrapper for cusparseSpMatDescr_t for the double precision data.
template<>
void create_cusparse_vector< float > (cusparseDnVecDescr_t &cusparse_vector, const LongIndexType vector_size, float *device_vector)
A template wrapper for cusparseDnVecDescr_t for the float precision data.
template<>
void create_cusparse_vector< double > (cusparseDnVecDescr_t &cusparse_vector, const LongIndexType vector_size, double *device_vector)
A template wrapper for cusparseDnVecDescr_t for the double precision data.
void destroy_cusparse_matrix (cusparseSpMatDescr_t &cusparse_matrix)
Destroys cusparse matrix.
void destroy_cusparse_vector (cusparseDnVecDescr_t &cusparse_vector)
Destroys cusparse vector.
template<>
void cusparse_matrix_buffer_size< float > (cusparseHandle_t cusparse_handle, cusparseOperation_t cusparse_operation, const float alpha, cusparseSpMatDescr_t cusparse_matrix, cusparseDnVecDescr_t cusparse_input_vector, const float beta, cusparseDnVecDescr_t cusparse_output_vector, cusparseSpMVAlg_t algorithm, size_t *buffer_size)
A template wrapper for cusparseSpMat_buffersize for float precision data. This function determines the buffer size needed for matrix-vector multiplication using cusparseSpMV. The output is buffer_size variable.
template<>
void cusparse_matrix_buffer_size< double > (cusparseHandle_t cusparse_handle, cusparseOperation_t cusparse_operation, const double alpha, cusparseSpMatDescr_t cusparse_matrix, cusparseDnVecDescr_t cusparse_input_vector, const double beta, cusparseDnVecDescr_t cusparse_output_vector, cusparseSpMVAlg_t algorithm, size_t *buffer_size)
A template wrapper for cusparseSpMat_buffersize for double precision data. This function determines the buffer size needed for matrix-vector multiplication using cusparseSpMV. The output is buffer_size variable.
template<>
void cusparse_matvec< float > (cusparseHandle_t cusparse_handle, cusparseOperation_t cusparse_operation, const float alpha, cusparseSpMatDescr_t cusparse_matrix, cusparseDnVecDescr_t cusparse_input_vector, const float beta, cusparseDnVecDescr_t cusparse_output_vector, cusparseSpMVAlg_t algorithm, void *external_buffer)
A wrapper for cusparseSpMV to perform sparse matrix-vector multiplication uasing float precision data.
template<>
void cusparse_matvec< double > (cusparseHandle_t cusparse_handle, cusparseOperation_t cusparse_operation, const double alpha, cusparseSpMatDescr_t cusparse_matrix, cusparseDnVecDescr_t cusparse_input_vector, const double beta, cusparseDnVecDescr_t cusparse_output_vector, cusparseSpMVAlg_t algorithm, void *external_buffer)
A wrapper for cusparseSpMV to perform sparse matrix-vector multiplication uasing double precision data.
template<typename DataType >
void create_cusparse_matrix (cusparseSpMatDescr_t &cusparse_matrix, const LongIndexType num_rows, const LongIndexType num_columns, const LongIndexType nnz, DataType *device_A_data, LongIndexType *device_A_indices, LongIndexType *device_A_index_pointer)
template<typename DataType >
void create_cusparse_vector (cusparseDnVecDescr_t &cusparse_vector, const LongIndexType vector_size, DataType *device_vector)
template<typename DataType >
void cusparse_matrix_buffer_size (cusparseHandle_t cusparse_handle, cusparseOperation_t cusparse_operation, const DataType alpha, cusparseSpMatDescr_t cusparse_matrix, cusparseDnVecDescr_t cusparse_input_vector, const DataType beta, cusparseDnVecDescr_t cusparse_output_vector, cusparseSpMVAlg_t algorithm, size_t *buffer_size)
template<typename DataType >
void cusparse_matvec (cusparseHandle_t cusparse_handle, cusparseOperation_t cusparse_operation, const DataType alpha, cusparseSpMatDescr_t cusparse_matrix, cusparseDnVecDescr_t cusparse_input_vector, const DataType beta, cusparseDnVecDescr_t cusparse_output_vector, cusparseSpMVAlg_t algorithm, void *external_buffer)
Detailed Description
A collection of templates to wrapper cusparse functions.
Note
The implementation in the cu file is wrapped inside the namepsace clause. This is not necessary in general, however, it is needed to avoid the old gcc compiler error (this is a gcc bug) which complains "no instance of function template matches the argument list const float".
Function Documentation
create_cusparse_matrix()
template<typename DataType > void cusparse_interface::create_cusparse_matrix (cusparseSpMatDescr_t & cusparse_matrix, const LongIndexType num_rows, const LongIndexType num_columns, const LongIndexType nnz, DataType * device_A_data, LongIndexType * device_A_indices, LongIndexType * device_A_index_pointer)
Referenced by cuCSCMatrix< DataType >::copy_host_to_device(), and cuCSRMatrix< DataType >::copy_host_to_device().
create_cusparse_matrix< double >()
template<> void cusparse_interface::create_cusparse_matrix< double > (cusparseSpMatDescr_t & cusparse_matrix, const LongIndexType num_rows, const LongIndexType num_columns, const LongIndexType nnz, double * device_A_data, LongIndexType * device_A_indices, LongIndexType * device_A_index_pointer)
A template wrapper for cusparseSpMatDescr_t for the double precision data.
Definition at line 67 of file cusparse_interface.cu.
     {
         cusparseStatus_t status = cusparseCreateCsr(
                 &cusparse_matrix, num_rows, num_columns, nnz,
                 device_A_index_pointer, device_A_indices, device_A_data,
                 CUSPARSE_INDEX_32I, CUSPARSE_INDEX_32I,
                 CUSPARSE_INDEX_BASE_ZERO, CUDA_R_64F);
         assert(status == CUSPARSE_STATUS_SUCCESS);
     }
References cusparseCreateCsr().
create_cusparse_matrix< float >()
template<> void cusparse_interface::create_cusparse_matrix< float > (cusparseSpMatDescr_t & cusparse_matrix, const LongIndexType num_rows, const LongIndexType num_columns, const LongIndexType nnz, float * device_A_data, LongIndexType * device_A_indices, LongIndexType * device_A_index_pointer)
A template wrapper for cusparseSpMatDescr_t for the float precision data.
Definition at line 40 of file cusparse_interface.cu.
     {
         cusparseStatus_t status = cusparseCreateCsr(
                 &cusparse_matrix, num_rows, num_columns, nnz,
                 device_A_index_pointer, device_A_indices, device_A_data,
                 CUSPARSE_INDEX_32I, CUSPARSE_INDEX_32I,
                 CUSPARSE_INDEX_BASE_ZERO, CUDA_R_32F);
         assert(status == CUSPARSE_STATUS_SUCCESS);
     }
References cusparseCreateCsr().
create_cusparse_vector()
template<typename DataType > void cusparse_interface::create_cusparse_vector (cusparseDnVecDescr_t & cusparse_vector, const LongIndexType vector_size, DataType * device_vector)
Referenced by cuCSCMatrix< DataType >::dot(), cuCSRMatrix< DataType >::dot(), cuCSCMatrix< DataType >::dot_plus(), cuCSRMatrix< DataType >::dot_plus(), cuCSCMatrix< DataType >::transpose_dot(), cuCSRMatrix< DataType >::transpose_dot(), cuCSCMatrix< DataType >::transpose_dot_plus(), and cuCSRMatrix< DataType >::transpose_dot_plus().
create_cusparse_vector< double >()
template<> void cusparse_interface::create_cusparse_vector< double > (cusparseDnVecDescr_t & cusparse_vector, const LongIndexType vector_size, double * device_vector)
A template wrapper for cusparseDnVecDescr_t for the double precision data.
Note that according to the cusparse documentation for the function cusparseCreateDnVec, it is safe to use const_cast to cast the input vector.
Definition at line 122 of file cusparse_interface.cu.
     {
         cusparseStatus_t status = cusparseCreateDnVec(
                 &cusparse_vector, vector_size, device_vector, CUDA_R_64F);
         assert(status == CUSPARSE_STATUS_SUCCESS);
     }
References cusparseCreateDnVec().
create_cusparse_vector< float >()
template<> void cusparse_interface::create_cusparse_vector< float > (cusparseDnVecDescr_t & cusparse_vector, const LongIndexType vector_size, float * device_vector)
A template wrapper for cusparseDnVecDescr_t for the float precision data.
Note that according to the cusparse documentation for the function cusparseCreateDnVec, it is safe to use const_cast to cast the input vector.
Definition at line 98 of file cusparse_interface.cu.
     {
         cusparseStatus_t status = cusparseCreateDnVec(
                 &cusparse_vector, vector_size, device_vector, CUDA_R_32F);
         assert(status == CUSPARSE_STATUS_SUCCESS);
     }
References cusparseCreateDnVec().
cusparse_matrix_buffer_size()
template<typename DataType > void cusparse_interface::cusparse_matrix_buffer_size (cusparseHandle_t cusparse_handle, cusparseOperation_t cusparse_operation, const DataType alpha, cusparseSpMatDescr_t cusparse_matrix, cusparseDnVecDescr_t cusparse_input_vector, const DataType beta, cusparseDnVecDescr_t cusparse_output_vector, cusparseSpMVAlg_t algorithm, size_t * buffer_size)
Referenced by cuCSCMatrix< DataType >::allocate_buffer(), and cuCSRMatrix< DataType >::allocate_buffer().
cusparse_matrix_buffer_size< double >()
template<> void cusparse_interface::cusparse_matrix_buffer_size< double > (cusparseHandle_t cusparse_handle, cusparseOperation_t cusparse_operation, const double alpha, cusparseSpMatDescr_t cusparse_matrix, cusparseDnVecDescr_t cusparse_input_vector, const double beta, cusparseDnVecDescr_t cusparse_output_vector, cusparseSpMVAlg_t algorithm, size_t * buffer_size)
A template wrapper for cusparseSpMat_buffersize for double precision data. This function determines the buffer size needed for matrix-vector multiplication using cusparseSpMV. The output is buffer_size variable.
Definition at line 204 of file cusparse_interface.cu.
     {
         cusparseStatus_t status = cusparseSpMV_bufferSize(
                 cusparse_handle, cusparse_operation, &alpha, cusparse_matrix,
                 cusparse_input_vector, &beta, cusparse_output_vector,
                 CUDA_R_64F, algorithm, buffer_size);
         assert(status == CUSPARSE_STATUS_SUCCESS);
     }
References cusparseSpMV_bufferSize().
cusparse_matrix_buffer_size< float >()
template<> void cusparse_interface::cusparse_matrix_buffer_size< float > (cusparseHandle_t cusparse_handle, cusparseOperation_t cusparse_operation, const float alpha, cusparseSpMatDescr_t cusparse_matrix, cusparseDnVecDescr_t cusparse_input_vector, const float beta, cusparseDnVecDescr_t cusparse_output_vector, cusparseSpMVAlg_t algorithm, size_t * buffer_size)
A template wrapper for cusparseSpMat_buffersize for float precision data. This function determines the buffer size needed for matrix-vector multiplication using cusparseSpMV. The output is buffer_size variable.
Definition at line 174 of file cusparse_interface.cu.
     {
         cusparseStatus_t status = cusparseSpMV_bufferSize(
                 cusparse_handle, cusparse_operation, &alpha, cusparse_matrix,
                 cusparse_input_vector, &beta, cusparse_output_vector,
                 CUDA_R_32F, algorithm, buffer_size);
         assert(status == CUSPARSE_STATUS_SUCCESS);
     }
References cusparseSpMV_bufferSize().
cusparse_matvec()
template<typename DataType > void cusparse_interface::cusparse_matvec (cusparseHandle_t cusparse_handle, cusparseOperation_t cusparse_operation, const DataType alpha, cusparseSpMatDescr_t cusparse_matrix, cusparseDnVecDescr_t cusparse_input_vector, const DataType beta, cusparseDnVecDescr_t cusparse_output_vector, cusparseSpMVAlg_t algorithm, void * external_buffer)
Referenced by cuCSCMatrix< DataType >::dot(), cuCSRMatrix< DataType >::dot(), cuCSCMatrix< DataType >::dot_plus(), cuCSRMatrix< DataType >::dot_plus(), cuCSCMatrix< DataType >::transpose_dot(), cuCSRMatrix< DataType >::transpose_dot(), cuCSCMatrix< DataType >::transpose_dot_plus(), and cuCSRMatrix< DataType >::transpose_dot_plus().
cusparse_matvec< double >()
template<> void cusparse_interface::cusparse_matvec< double > (cusparseHandle_t cusparse_handle, cusparseOperation_t cusparse_operation, const double alpha, cusparseSpMatDescr_t cusparse_matrix, cusparseDnVecDescr_t cusparse_input_vector, const double beta, cusparseDnVecDescr_t cusparse_output_vector, cusparseSpMVAlg_t algorithm, void * external_buffer)
A wrapper for cusparseSpMV to perform sparse matrix-vector multiplication uasing double precision data.
Definition at line 263 of file cusparse_interface.cu.
     {
         cusparseStatus_t status = cusparseSpMV(cusparse_handle,
                                                cusparse_operation, &alpha,
                                                cusparse_matrix,
                                                cusparse_input_vector, &beta,
                                                cusparse_output_vector,
                                                CUDA_R_64F, algorithm,
                                                external_buffer);
         assert(status == CUSPARSE_STATUS_SUCCESS);
     }
References cusparseSpMV().
cusparse_matvec< float >()
template<> void cusparse_interface::cusparse_matvec< float > (cusparseHandle_t cusparse_handle, cusparseOperation_t cusparse_operation, const float alpha, cusparseSpMatDescr_t cusparse_matrix, cusparseDnVecDescr_t cusparse_input_vector, const float beta, cusparseDnVecDescr_t cusparse_output_vector, cusparseSpMVAlg_t algorithm, void * external_buffer)
A wrapper for cusparseSpMV to perform sparse matrix-vector multiplication uasing float precision data.
Definition at line 232 of file cusparse_interface.cu.
     {
         cusparseStatus_t status = cusparseSpMV(cusparse_handle,
                                                cusparse_operation, &alpha,
                                                cusparse_matrix,
                                                cusparse_input_vector, &beta,
                                                cusparse_output_vector,
                                                CUDA_R_32F, algorithm,
                                                external_buffer);
         assert(status == CUSPARSE_STATUS_SUCCESS);
     }
References cusparseSpMV().
destroy_cusparse_matrix()
void cusparse_interface::destroy_cusparse_matrix (cusparseSpMatDescr_t & cusparse_matrix)
Destroys cusparse matrix.
Definition at line 141 of file cusparse_interface.cu.
     {
         cusparseStatus_t status = cusparseDestroySpMat(cusparse_matrix);
         assert(status == CUSPARSE_STATUS_SUCCESS);
     }
References cusparseDestroySpMat().
Referenced by cuCSCMatrix< DataType >::~cuCSCMatrix(), and cuCSRMatrix< DataType >::~cuCSRMatrix().
destroy_cusparse_vector()
void cusparse_interface::destroy_cusparse_vector (cusparseDnVecDescr_t & cusparse_vector)
Destroys cusparse vector.
Definition at line 156 of file cusparse_interface.cu.
     {
         cusparseStatus_t status = cusparseDestroyDnVec(cusparse_vector);
         assert(status == CUSPARSE_STATUS_SUCCESS);
     }
References cusparseDestroyDnVec().
Referenced by cuCSCMatrix< DataType >::dot(), cuCSRMatrix< DataType >::dot(), cuCSCMatrix< DataType >::dot_plus(), cuCSRMatrix< DataType >::dot_plus(), cuCSCMatrix< DataType >::transpose_dot(), cuCSRMatrix< DataType >::transpose_dot(), cuCSCMatrix< DataType >::transpose_dot_plus(), and cuCSRMatrix< DataType >::transpose_dot_plus().