imate: cublas_interface Namespace Reference
cublas_interface Namespace Reference
A collection of templates to wrapper cublas functions.
Functions
template<>
cublasStatus_t cublasXgemv< float > (cublasHandle_t handle, cublasOperation_t trans, int m, int n, const float *alpha, const float *A, int lda, const float *x, int incx, const float *beta, float *y, int incy)
A template wrapper for cublasSgemv.
template<>
cublasStatus_t cublasXgemv< double > (cublasHandle_t handle, cublasOperation_t trans, int m, int n, const double *alpha, const double *A, int lda, const double *x, int incx, const double *beta, double *y, int incy)
A template wrapper for cublasDgemv.
template<>
cublasStatus_t cublasXcopy< float > (cublasHandle_t handle, int n, const float *x, int incx, float *y, int incy)
A template wrapper for cublasScopy.
template<>
cublasStatus_t cublasXcopy< double > (cublasHandle_t handle, int n, const double *x, int incx, double *y, int incy)
A template wrapper for cublasDcopy.
template<>
cublasStatus_t cublasXaxpy< float > (cublasHandle_t handle, int n, const float *alpha, const float *x, int incx, float *y, int incy)
A template wrapper for cublasSaxpy.
template<>
cublasStatus_t cublasXaxpy< double > (cublasHandle_t handle, int n, const double *alpha, const double *x, int incx, double *y, int incy)
A template wrapper for cublasDaxpy.
template<>
cublasStatus_t cublasXdot< float > (cublasHandle_t handle, int n, const float *x, int incx, const float *y, int incy, float *result)
A template wrapper for cublasSdot.
template<>
cublasStatus_t cublasXdot< double > (cublasHandle_t handle, int n, const double *x, int incx, const double *y, int incy, double *result)
A template wrapper for cublasDdot.
template<>
cublasStatus_t cublasXnrm2< float > (cublasHandle_t handle, int n, const float *x, int incx, float *result)
A template wrapper to cublasSnrm2.
template<>
cublasStatus_t cublasXnrm2< double > (cublasHandle_t handle, int n, const double *x, int incx, double *result)
A template wrapper to cublasDnrm2.
template<>
cublasStatus_t cublasXscal< float > (cublasHandle_t handle, int n, const float *alpha, float *x, int incx)
A template wrapper for cublasSscal.
template<>
cublasStatus_t cublasXscal< double > (cublasHandle_t handle, int n, const double *alpha, double *x, int incx)
A template wrapper for cublasDscal.
template<typename DataType >
cublasStatus_t cublasXgemv (cublasHandle_t handle, cublasOperation_t trans, int m, int n, const DataType *alpha, const DataType *A, int lda, const DataType *x, int incx, const DataType *beta, DataType *y, int incy)
template<typename DataType >
cublasStatus_t cublasXcopy (cublasHandle_t handle, int n, const DataType *x, int incx, DataType *y, int incy)
template<typename DataType >
cublasStatus_t cublasXaxpy (cublasHandle_t handle, int n, const DataType *alpha, const DataType *x, int incx, DataType *y, int incy)
template<typename DataType >
cublasStatus_t cublasXdot (cublasHandle_t handle, int n, const DataType *x, int incx, const DataType *y, int incy, DataType *result)
template<typename DataType >
cublasStatus_t cublasXnrm2 (cublasHandle_t handle, int n, const DataType *x, int incx, DataType *result)
template<typename DataType >
cublasStatus_t cublasXscal (cublasHandle_t handle, int n, const DataType *alpha, DataType *x, int incx)
Detailed Description
A collection of templates to wrapper cublas functions.
Note
The implementation in the cu file is wrapped inside the namepsace clause. This is not necessary in general, however, it is needed to avoid the old gcc compiler error (this is a gcc bug) which complains "no instance of function template matches the argument list const float".
Function Documentation
cublasXaxpy()
template<typename DataType > cublasStatus_t cublas_interface::cublasXaxpy (cublasHandle_t handle, int n, const DataType * alpha, const DataType * x, int incx, DataType * y, int incy)
Referenced by cuVectorOperations< DataType >::subtract_scaled_vector().
cublasXaxpy< double >()
template<> cublasStatus_t cublas_interface::cublasXaxpy< double > (cublasHandle_t handle, int n, const double * alpha, const double * x, int incx, double * y, int incy)
A template wrapper for cublasDaxpy.
Definition at line 156 of file cublas_interface.cu.
     {
         return cublasDaxpy(handle, n, alpha, x, incx, y, incy);
     }
References cublasDaxpy().
cublasXaxpy< float >()
template<> cublasStatus_t cublas_interface::cublasXaxpy< float > (cublasHandle_t handle, int n, const float * alpha, const float * x, int incx, float * y, int incy)
A template wrapper for cublasSaxpy.
Definition at line 135 of file cublas_interface.cu.
     {
         return cublasSaxpy(handle, n, alpha, x, incx, y, incy);
     }
References cublasSaxpy().
cublasXcopy()
template<typename DataType > cublasStatus_t cublas_interface::cublasXcopy (cublasHandle_t handle, int n, const DataType * x, int incx, DataType * y, int incy)
Referenced by cuVectorOperations< DataType >::copy_scaled_vector(), and cuVectorOperations< DataType >::copy_vector().
cublasXcopy< double >()
template<> cublasStatus_t cublas_interface::cublasXcopy< double > (cublasHandle_t handle, int n, const double * x, int incx, double * y, int incy)
A template wrapper for cublasDcopy.
Definition at line 115 of file cublas_interface.cu.
     {
         return cublasDcopy(handle, n, x, incx, y, incy);
     }
References cublasDcopy().
cublasXcopy< float >()
template<> cublasStatus_t cublas_interface::cublasXcopy< float > (cublasHandle_t handle, int n, const float * x, int incx, float * y, int incy)
A template wrapper for cublasScopy.
Definition at line 95 of file cublas_interface.cu.
     {
         return cublasScopy(handle, n, x, incx, y, incy);
     }
References cublasScopy().
cublasXdot()
template<typename DataType > cublasStatus_t cublas_interface::cublasXdot (cublasHandle_t handle, int n, const DataType * x, int incx, const DataType * y, int incy, DataType * result)
Referenced by cuVectorOperations< DataType >::inner_product().
cublasXdot< double >()
template<> cublasStatus_t cublas_interface::cublasXdot< double > (cublasHandle_t handle, int n, const double * x, int incx, const double * y, int incy, double * result)
A template wrapper for cublasDdot.
Definition at line 198 of file cublas_interface.cu.
     {
         return cublasDdot(handle, n, x, incx, y, incy, result);
     }
References cublasDdot().
cublasXdot< float >()
template<> cublasStatus_t cublas_interface::cublasXdot< float > (cublasHandle_t handle, int n, const float * x, int incx, const float * y, int incy, float * result)
A template wrapper for cublasSdot.
Definition at line 177 of file cublas_interface.cu.
     {
         return cublasSdot(handle, n, x, incx, y, incy, result);
     }
References cublasSdot().
cublasXgemv()
template<typename DataType > cublasStatus_t cublas_interface::cublasXgemv (cublasHandle_t handle, cublasOperation_t trans, int m, int n, const DataType * alpha, const DataType * A, int lda, const DataType * x, int incx, const DataType * beta, DataType * y, int incy)
Referenced by cuMatrixOperations< DataType >::dense_matvec(), cuMatrixOperations< DataType >::dense_matvec_plus(), cuMatrixOperations< DataType >::dense_transposed_matvec(), and cuMatrixOperations< DataType >::dense_transposed_matvec_plus().
cublasXgemv< double >()
template<> cublasStatus_t cublas_interface::cublasXgemv< double > (cublasHandle_t handle, cublasOperation_t trans, int m, int n, const double * alpha, const double * A, int lda, const double * x, int incx, const double * beta, double * y, int incy)
A template wrapper for cublasDgemv.
Definition at line 67 of file cublas_interface.cu.
     {
         return cublasDgemv(handle, trans, m, n, alpha, A, lda, x, incx, beta,
                            y, incy);
     }
cublasXgemv< float >()
template<> cublasStatus_t cublas_interface::cublasXgemv< float > (cublasHandle_t handle, cublasOperation_t trans, int m, int n, const float * alpha, const float * A, int lda, const float * x, int incx, const float * beta, float * y, int incy)
A template wrapper for cublasSgemv.
Definition at line 40 of file cublas_interface.cu.
     {
         return cublasSgemv(handle, trans, m, n, alpha, A, lda, x, incx, beta,
                            y, incy);
     }
cublasXnrm2()
template<typename DataType > cublasStatus_t cublas_interface::cublasXnrm2 (cublasHandle_t handle, int n, const DataType * x, int incx, DataType * result)
Referenced by cuVectorOperations< DataType >::euclidean_norm().
cublasXnrm2< double >()
template<> cublasStatus_t cublas_interface::cublasXnrm2< double > (cublasHandle_t handle, int n, const double * x, int incx, double * result)
A template wrapper to cublasDnrm2.
Definition at line 238 of file cublas_interface.cu.
     {
         return cublasDnrm2(handle, n, x, incx, result);
     }
References cublasDnrm2().
cublasXnrm2< float >()
template<> cublasStatus_t cublas_interface::cublasXnrm2< float > (cublasHandle_t handle, int n, const float * x, int incx, float * result)
A template wrapper to cublasSnrm2.
Definition at line 219 of file cublas_interface.cu.
     {
         return cublasSnrm2(handle, n, x, incx, result);
     }
References cublasSnrm2().
cublasXscal()
template<typename DataType > cublasStatus_t cublas_interface::cublasXscal (cublasHandle_t handle, int n, const DataType * alpha, DataType * x, int incx)
Referenced by cuVectorOperations< DataType >::copy_scaled_vector(), and cuVectorOperations< DataType >::normalize_vector_in_place().
cublasXscal< double >()
template<> cublasStatus_t cublas_interface::cublasXscal< double > (cublasHandle_t handle, int n, const double * alpha, double * x, int incx)
A template wrapper for cublasDscal.
Definition at line 276 of file cublas_interface.cu.
     {
         return cublasDscal(handle, n, alpha, x, incx);
     }
References cublasDscal().
cublasXscal< float >()
template<> cublasStatus_t cublas_interface::cublasXscal< float > (cublasHandle_t handle, int n, const float * alpha, float * x, int incx)
A template wrapper for cublasSscal.
Definition at line 257 of file cublas_interface.cu.
     {
         return cublasSscal(handle, n, alpha, x, incx);
     }
References cublasSscal().