imate: /home/runner/work/imate/imate/imate/_cuda_utilities/query_device.h File Reference
query_device.h File Reference
#include "./device_properties.h"
Functions
void query_device (DeviceProperties &device_properties)
Queries GPU device information, such as the number of devices, number of multiprocessors, and the number of threads per each multiprocessor.
Function Documentation
query_device()
void query_device (DeviceProperties & device_properties)
Queries GPU device information, such as the number of devices, number of multiprocessors, and the number of threads per each multiprocessor.
Parameters
[out] device_properties A struct to be filled with the number of devices, threads and multiprocessors.
Definition at line 31 of file query_device.cu.
 {
     // Query number of devices
     int num_devices;
     cudaError_t error = cudaGetDeviceCount(&num_devices);
     if (error != cudaSuccess)
     {
         return;
     }
     // Set number of devices
     device_properties.set_num_devices(num_devices);
     // Read properties of each device
     struct cudaDeviceProp properties;
     for (int device = 0; device < num_devices; ++device)
     {
         cudaGetDeviceProperties(&properties, device);
         // Machines with no GPUs may still report one emulation device
         if (properties.major == 9999)
         {
             // This is a gpu emulation not an actual device
             device_properties.num_multiprocessors[device] = 0;
             device_properties.num_threads_per_multiprocessor[device] = 0;
         }
         else
         {
             device_properties.num_multiprocessors[device] = \
                 properties.multiProcessorCount;
             device_properties.num_threads_per_multiprocessor[device] = \
                 properties.maxThreadsPerMultiProcessor;
         }
     }
 }
References cudaGetDeviceCount(), cudaGetDeviceProperties(), DeviceProperties::num_multiprocessors, DeviceProperties::num_threads_per_multiprocessor, and DeviceProperties::set_num_devices().